const HEROES = [
  { id:'rogue', name:'Nyx', role:'Rogue', icon:'🗡️', art:'assets/heroes/nyx-rogue.webp', hp:24, passive:'Opportunist', start:{name:'Backstab', icon:'🗡️', desc:'Deal 8 damage. +4 if the enemy is below half health.', type:'damage', value:8, execute:4} },
  { id:'guardian', name:'Bram', role:'Guardian', icon:'🛡️', art:'assets/heroes/bram-guardian.webp', hp:34, passive:'Steadfast', start:{name:'Protect', icon:'🛡️', desc:'Deal 4 damage and restore 5 party health.', type:'hybrid', value:4, heal:5} },
  { id:'witch', name:'Mora', role:'Veilborn Witch', icon:'🔮', art:'assets/heroes/mora-veilborn-warlock-v2.webp', hp:22, passive:'Lingering Curse', start:{name:'Hex', icon:'🕸️', desc:'Deal 6 damage and weaken the next enemy attack.', type:'weaken', value:6} },
  { id:'ranger', name:'Ash', role:'Ranger', icon:'🏹', art:'assets/heroes/ash-ranger.webp', hp:26, passive:'Keen Eye', start:{name:'Twin Shot', icon:'🏹', desc:'Deal 7 damage with a chance to strike twice.', type:'double', value:7} },
  { id:'cleric', name:'Sol', role:'Cleric', icon:'☀️', art:'assets/heroes/sol-cleric.webp', hp:28, passive:'Last Light', start:{name:'Radiance', icon:'☀️', desc:'Deal 5 damage and heal the most wounded hero for 7.', type:'hybrid', value:5, heal:7} }
];

const ABILITIES = [
 {name:'Poisoned Edge',icon:'🧪',desc:'Deal 6 damage now and 3 after every enemy turn.',type:'poison',value:6},
 {name:'Shadowstep',icon:'🌘',desc:'Deal 7 damage and evade the next enemy attack.',type:'evade',value:7},
 {name:'Blood Pact',icon:'🩸',desc:'Lose 3 health to deal 14 damage.',type:'pact',value:14},
 {name:'Chain Lightning',icon:'⚡',desc:'Deal 10 damage. Strong, simple, reliable.',type:'damage',value:10},
 {name:'Mend Fate',icon:'🧵',desc:'Heal the entire party for 6.',type:'heal',value:6},
 {name:'Vanguard',icon:'⚔️',desc:'Deal 5 damage and restore 8 health to yourself.',type:'selfheal',value:5,heal:8},
 {name:'Expose',icon:'👁️',desc:'Deal 5 damage; the next hero deals +6.',type:'expose',value:5},
 {name:'Soul Siphon',icon:'🕯️',desc:'Deal 7 damage and heal the most wounded hero for 5.',type:'hybrid',value:7,heal:5},
 {name:'Meteor',icon:'☄️',desc:'Deal 16 damage, then this ability becomes exhausted.',type:'meteor',value:16},
 {name:'Battle Cry',icon:'📯',desc:'Deal 4 damage and empower the next two attacks by 3.',type:'cry',value:4},
 {name:'Silent Cut',icon:'🤫',desc:'Deal 9 damage before the enemy can react.',type:'damage',value:9},
 {name:'Smoke Veil',icon:'💨',desc:'Deal 5 damage and evade the next enemy attack.',type:'evade',value:5},
 {name:'Purifying Wave',icon:'💧',desc:'Heal the entire party for 5.',type:'heal',value:5},
 {name:'Iron Resolve',icon:'⛓️',desc:'Deal 4 damage and restore 10 health to yourself.',type:'selfheal',value:4,heal:10},
 {name:'Mark Prey',icon:'🎯',desc:'Deal 4 damage; the next hero deals +6.',type:'expose',value:4},
 {name:'Venom Bloom',icon:'🐍',desc:'Deal 5 damage now and 3 after every enemy turn.',type:'poison',value:5},
 {name:'Dark Bargain',icon:'🫀',desc:'Lose 3 health to deal 13 damage.',type:'pact',value:13},
 {name:'Thunderclap',icon:'🌩️',desc:'Deal 7 damage and weaken the next enemy attack.',type:'weaken',value:7},
 {name:'Lifebloom',icon:'🌺',desc:'Deal 4 damage and heal the most wounded hero for 8.',type:'hybrid',value:4,heal:8},
 {name:'Falling Star',icon:'🌠',desc:'Deal 15 damage, then this ability becomes exhausted.',type:'meteor',value:15},
 {name:'War Drums',icon:'🥁',desc:'Deal 3 damage and empower the next two attacks by 3.',type:'cry',value:3},
 {name:"Executioner's Arc",icon:'🪓',desc:'Deal 12 heavy damage.',type:'damage',value:12},
 {name:'Phase Lance',icon:'🌀',desc:'Deal 8 damage and evade the next enemy attack.',type:'evade',value:8},
 {name:'Rejuvenating Rain',icon:'🌧️',desc:'Heal the entire party for 5.',type:'heal',value:5},
 {name:'Leeching Brand',icon:'🦷',desc:'Deal 8 damage and heal the most wounded hero for 4.',type:'hybrid',value:8,heal:4},
 {name:'Crippling Shot',icon:'🪶',desc:'Deal 8 damage and weaken the next enemy attack.',type:'weaken',value:8},
 {name:'Oathbreaker',icon:'⚔️',desc:'Deal 6 damage with a chance to strike twice.',type:'double',value:6},
 {name:'Ember Ward',icon:'🕯️',desc:'Deal 6 damage and restore 6 health to yourself.',type:'selfheal',value:6,heal:6},
 {name:'Death Mark',icon:'☠️',desc:'Deal 6 damage; the next hero deals +6.',type:'expose',value:6},
 {name:'Serpent Strike',icon:'🐉',desc:'Deal 7 damage now and 3 after every enemy turn.',type:'poison',value:7},
 {name:'Grave Needle',icon:'🪡',desc:'Deal 9 precise damage.',type:'damage',value:9},
 {name:'Aegis Pulse',icon:'🔆',desc:'Deal 5 damage and heal the most wounded hero for 6.',type:'hybrid',value:5,heal:6},
 {name:'Witchfire',icon:'🟣',desc:'Deal 9 damage and weaken the next enemy attack.',type:'weaken',value:9},
 {name:'Moon Salve',icon:'🌙',desc:'Heal the entire party for 7.',type:'heal',value:7},
 {name:'Razorwind',icon:'🌪️',desc:'Deal 8 damage with a chance to strike twice.',type:'double',value:8},
 {name:'Phantom Guard',icon:'👤',desc:'Deal 6 damage and evade the next enemy attack.',type:'evade',value:6},
 {name:'Ruinous Oath',icon:'📜',desc:'Lose 3 health to deal 15 damage.',type:'pact',value:15},
 {name:'Rotfang',icon:'🦠',desc:'Deal 8 damage now and 3 after every enemy turn.',type:'poison',value:8},
 {name:'Sun Spear',icon:'🌞',desc:'Deal 11 radiant damage.',type:'damage',value:11},
 {name:'Mercy Chain',icon:'⛓️',desc:'Deal 6 damage and heal the most wounded hero for 7.',type:'hybrid',value:6,heal:7},
 {name:"Predator's Mark",icon:'🐾',desc:'Deal 7 damage; the next hero deals +6.',type:'expose',value:7},
 {name:'Stoneblood',icon:'🪨',desc:'Deal 7 damage and restore 9 health to yourself.',type:'selfheal',value:7,heal:9},
 {name:'Veil Collapse',icon:'🕳️',desc:'Deal 17 damage, then this ability becomes exhausted.',type:'meteor',value:17},
 {name:'Marching Hymn',icon:'🎺',desc:'Deal 5 damage and empower the next two attacks by 3.',type:'cry',value:5},
 {name:'Dusk Bolt',icon:'🌆',desc:'Deal 10 shadow damage.',type:'damage',value:10},
 {name:'Thornskin',icon:'🌵',desc:'Deal 5 damage and restore 11 health to yourself.',type:'selfheal',value:5,heal:11},
 {name:'Blinding Ash',icon:'🌫️',desc:'Deal 6 damage and weaken the next enemy attack.',type:'weaken',value:6},
 {name:'Night Venom',icon:'🦂',desc:'Deal 6 damage now and 3 after every enemy turn.',type:'poison',value:6},
 {name:'Silver Volley',icon:'🪶',desc:'Deal 7 damage with a chance to strike twice.',type:'double',value:7},
 {name:'Fate Rend',icon:'✂️',desc:'Deal 8 damage; the next hero deals +6.',type:'expose',value:8}
];

const REWARD_ABILITY_NAMES = ['Poisoned Edge','Shadowstep','Blood Pact','Chain Lightning','Mend Fate','Vanguard','Expose','Soul Siphon','Meteor','Battle Cry','Thunderclap','Oathbreaker'];
const REWARD_ABILITIES = REWARD_ABILITY_NAMES.map(name=>ABILITIES.find(a=>a.name===name));
const MAX_ABILITY_RANK = 5;
const DUPLICATE_CHANCE = .18;

function abilityText(a){let dot=a.dot||3,weaken=a.weaken||4,bonus=a.bonus||6,power=a.power||3;if(a.type==='damage')return `Deal ${a.value} damage${a.execute?`. +${a.execute} below half health.`:'.'}`;if(a.type==='hybrid')return `Deal ${a.value} damage and heal the most wounded hero for ${a.heal}.`;if(a.type==='weaken')return `Deal ${a.value} damage and reduce the next enemy attack by ${weaken}.`;if(a.type==='double')return `Deal ${a.value} damage with a 45% chance to strike twice.`;if(a.type==='poison')return `Deal ${a.value} damage and add ${dot} poison after every enemy turn.`;if(a.type==='evade')return `Deal ${a.value} damage and evade the next enemy attack.`;if(a.type==='pact')return `Lose 3 health to deal ${a.value} damage.`;if(a.type==='heal')return `Heal the entire party for ${a.value}.`;if(a.type==='selfheal')return `Deal ${a.value} damage and restore ${a.heal} health to yourself.`;if(a.type==='expose')return `Deal ${a.value} damage; the next hero deals +${bonus}.`;if(a.type==='meteor')return `Deal ${a.value} damage, then this ability becomes exhausted.`;if(a.type==='cry')return `Deal ${a.value} damage and empower the next two attacks by ${power}.`;return a.desc;}
function rankUpAbility(a){a.rank=Math.min(MAX_ABILITY_RANK,(a.rank||1)+1);let gain=a.type==='meteor'?3:['damage','pact'].includes(a.type)?2:1;if(typeof a.value==='number')a.value+=gain;if(a.heal)a.heal+=2;if(a.type==='poison')a.dot=(a.dot||3)+1;if(a.type==='weaken')a.weaken=(a.weaken||4)+1;if(a.type==='expose')a.bonus=(a.bonus||6)+2;if(a.type==='cry')a.power=(a.power||3)+1;a.desc=abilityText(a);return a;}
function rankPreview(a){return rankUpAbility({...a});}

const WORLDS = [
 {name:'The Verdant Oath',tone:'Before the kingdom fell',color:'#70c69b',mobs:[
  ['Thorn Wretch','🌿',18,4,'assets/enemies/thorn-wretch.webp',2,'Normal',{name:'The Forest Threshold',bg:'assets/scenes/verdant-1-threshold.webp',cutout:'assets/enemies/cinematic/thorn-wretch-cutout.webp',intro:'The old road ends beneath a wall of ancient trees. Two figures tear themselves free from the thorn-choked verge.',outro:'The Wretches collapse into lifeless roots. Beyond them, a narrow trail winds beneath the canopy—and something deeper in the forest begins to howl.'}],
  ['Briar Hound','🐺',18,5,'assets/enemies/briar-hound.webp',3,'Normal',{name:"The Hunter's Trail",bg:'assets/scenes/verdant-2-trail.webp',cutout:'assets/enemies/cinematic/briar-hound-cutout.webp',intro:'The canopy swallows the last daylight. Claw marks score the trunks, and three Briar Hounds circle the party through the mist.',outro:'The Briar Hound pack falls silent. Their tracks lead deeper, toward a hollow where violet spores drift between the trees.'}],
  ['Spore Stalker','🍄',24,6,'assets/enemies/spore-stalker.webp',2,'Normal',{name:'The Fungal Hollow',bg:'assets/scenes/verdant-3-hollow.webp',cutout:'assets/enemies/cinematic/spore-stalker-cutout.webp',intro:'The trail dissolves into black water and luminous fungus. Two tall shapes unfold beneath pale mushroom crowns.',outro:'The Stalkers burst into clouds of dying spores. Through the clearing, broken shrine stones point toward the forest’s oldest path.'}],
  ['Mossbound Ogre','🧌',58,9,'assets/enemies/mossbound-ogre.webp',1,'Elite',{name:'The Broken Grove',bg:'assets/scenes/verdant-4-shrine.webp',cutout:'assets/enemies/cinematic/mossbound-ogre-cutout.webp',intro:'A ruined oath-shrine blocks the way. Its massive guardian rises from the altar, dragging a shattered pillar behind it.',outro:'The Ogre crashes through the ancient altar. Beneath the rubble, living roots twist into a staircase descending toward the heart of the forest.'}],
  ['The Root King','👑',78,11,'assets/enemies/root-king.webp',1,'Boss',{name:'The Heartroot Throne',bg:'assets/scenes/verdant-5-throne.webp',cutout:'assets/enemies/cinematic/root-king-cutout.webp',intro:'The forest opens into a cathedral of roots and black water. Upon the throne, an emerald gaze awakens beneath a crown of branches.',outro:'The Root King’s crown splits and the corruption recoils. For one breath, the forest remembers what it was before the worlds began to fall.'}]
 ]},
 {name:'The Ashen Wake',tone:'After the first flame died',color:'#d08a62',mobs:[['Cinder Hound','🐺',42,8,null,1,'Normal'],['Ember Imps','👹',24,5,null,2,'Normal'],['Ash Revenant','💀',54,10,null,1,'Normal'],['Furnace Knight','♜',68,12,null,1,'Elite'],['The Pyre Saint','🔥',92,14,null,1,'Boss']]},
 {name:'The Frozen Hour',tone:'Where time refuses to move',color:'#77b9dd',mobs:[['Glass Wraith','👻',48,9,null,1,'Normal'],['Rimefangs','🐺',28,6,null,2,'Normal'],['Frost Seer','🧙',60,11,null,1,'Normal'],['Frost Colossus','🗿',78,13,null,1,'Elite'],['The Pale Clock','🕰️',104,15,null,1,'Boss']]},
 {name:'The Hollow Court',tone:'A kingdom that remembers you',color:'#a783cf',mobs:[['Empty Knight','♞',58,11,null,1,'Normal'],['Whisper Shades','👤',32,7,null,2,'Normal'],['Grief Eater','🦇',72,13,null,1,'Normal'],['Mirror Champion','🪞',88,15,null,1,'Elite'],['The Echo Queen','👑',116,17,null,1,'Boss']]},
 {name:'The Fifth Reality',tone:'All your failures meet here',color:'#e4b66f',mobs:[['Worldless Choir','🎭',68,13,null,1,'Normal'],['Null Stalker','🕷️',76,14,null,1,'Normal'],['Fate Devourer','🐉',88,15,null,1,'Normal'],['Echo Tyrant','🜏',108,18,null,1,'Elite'],['The End of Five','🌑',140,20,null,1,'Boss']]}
];

let state = {screen:'title', selected:[], world:0, level:0, livesRemaining:5, encounterType:'Normal', encounterName:'', scene:null, sceneEntering:false, encounterIntro:false, cardsArriving:false, party:[], enemies:[], targetIndex:0, enemyTurnIndex:0, turn:0, inspectedHeroId:null, log:[], echoes:[], echoSerial:0, activeEchoId:null, echoMode:'summon', echoUsed:false, pendingEchoOptions:[], rewards:[], assigned:0, pendingReplacement:null, learnedAbilities:new Set(), evade:false, boost:0, boostPower:3, exhausted:new Set(), animating:false, fx:null};
const app = document.querySelector('#app');
let encounterIntroTimer=null;

function testNav(){if(state.screen!=='game')return '';return `<div class="test-nav" aria-label="Playtest encounter navigation"><span>Playtest</span><button onclick="jumpEncounter(-1)" ${state.level===0?'disabled':''} aria-label="Previous encounter">‹</button><b>${state.level+1}/5</b><button onclick="jumpEncounter(1)" ${state.level===4?'disabled':''} aria-label="Next encounter">›</button></div>`;}
function topbar(){return `<div class="topbar"><div class="brand">FIFTH ECHO</div><div class="run-meta">${testNav()}<div class="lives" aria-label="${state.livesRemaining} of 5 lives remain"><span>Lives <b>${state.livesRemaining}/5</b></span>${[0,1,2,3,4].map(i=>`<i class="life ${i>=state.livesRemaining?'lost':''}"></i>`).join('')}</div></div></div>`}
function render(){ if(state.screen==='title') title(); else if(state.screen==='select') select(); else game(); }
function title(){ app.innerHTML=`<div class="shell">${topbar()}<section class="panel hero"><div class="eyebrow">A party-building roguelite</div><h1>Fifth<br>Echo</h1><p>Five lives. Five collapsing realities. Every fallen hero can return as an Echo—and every ability you give them may decide the final battle.</p><button class="primary" onclick="state.screen='select';render()">Begin the first world</button></section></div>`; }
function activeEcho(){return state.echoes.find(e=>e.id===state.activeEchoId)||null;}
function echoArchive(){if(!state.echoes.length)return '';return `<section class="echo-archive panel"><div class="echo-archive-copy"><div class="eyebrow">The Echo Archive</div><h3>Choose one fallen support</h3><p><b>Recruit</b> triggers a reduced echo at every encounter. <b>Summon</b> keeps the full effect as a once-per-fight support card.</p></div><div class="echo-options">${state.echoes.map(e=>`<article class="echo-option ${state.activeEchoId===e.id?'active':''}"><div class="echo-option-art">${e.art?`<img src="${e.art}" alt="${e.name}'s Echo" />`:e.icon}</div><div><span>${e.role} Echo</span><h4>${e.name}</h4><p>${e.ability.icon} ${e.ability.name} · R${e.ability.rank||1}</p></div><div class="echo-mode-buttons"><button class="${state.activeEchoId===e.id&&state.echoMode==='recruit'?'selected':''}" aria-pressed="${state.activeEchoId===e.id&&state.echoMode==='recruit'}" onclick="setEchoMode('${e.id}','recruit')">Recruit</button><button class="${state.activeEchoId===e.id&&state.echoMode==='summon'?'selected':''}" aria-pressed="${state.activeEchoId===e.id&&state.echoMode==='summon'}" onclick="setEchoMode('${e.id}','summon')">Summon</button></div></article>`).join('')}</div></section>`;}
function setEchoMode(id,mode){if(!state.echoes.some(e=>e.id===id)||!['recruit','summon'].includes(mode))return;state.activeEchoId=id;state.echoMode=mode;render();}
function select(){ app.innerHTML=`<div class="shell">${topbar()}<div class="section-head"><div><div class="eyebrow">Form your expedition</div><h2>Choose three heroes</h2><p>Each begins with one signature ability. Their next abilities are yours to shape.</p></div><div><b>${state.livesRemaining}</b> lives remain · ${state.selected.length} / 3 chosen</div></div>${echoArchive()}<div class="roster">${HEROES.map(h=>`<button class="hero-card ${h.art?'with-art':''} ${state.selected.includes(h.id)?'selected':''}" onclick="toggleHero('${h.id}')"><div class="portrait-stage">${h.art?`<img class="hero-art" src="${h.art}" alt="${h.name}, ${h.role}" />`:`<div class="portrait">${h.icon}</div>`}<span class="vitality">♥ ${h.hp}</span></div><div class="card-copy"><div class="class">${h.role}</div><h3>${h.name}</h3><div class="signature"><span>${h.start.name}</span><b>${h.start.icon}</b></div><p>${h.start.desc}</p><div class="passive">${h.passive}</div></div></button>`).join('')}</div><div class="action-row"><button class="primary" ${state.selected.length!==3?'disabled':''} onclick="begin()">Enter the world</button></div></div>`; }
function toggleHero(id){ state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):(state.selected.length<3?[...state.selected,id]:state.selected); render(); }
function begin(){ state.party=state.selected.map(id=>{let h=HEROES.find(x=>x.id===id);return {...h,maxHp:h.hp,currentHp:h.hp,abilities:[{...h.start,rank:1}]}});state.party.forEach(h=>h.abilities.forEach(a=>state.learnedAbilities.add(a.name)));state.screen='game';startEncounter(); }
function startEncounter(){let m=WORLDS[state.world].mobs[state.level],count=m[5]||1;if(encounterIntroTimer)clearTimeout(encounterIntroTimer);state.encounterName=m[0];state.encounterType=m[6]||'Normal';state.scene=m[7]||null;state.enemies=Array.from({length:count},(_,i)=>({name:m[0],internalName:count>1?`${m[0]} ${String.fromCharCode(65+i)}`:m[0],slot:i,icon:m[1],art:m[4],maxHp:m[2],hp:m[2],damage:m[3],weakened:0,expose:0,poison:0}));state.targetIndex=0;state.enemyTurnIndex=0;state.turn=0;state.inspectedHeroId=state.party.find(h=>h.currentHp>0)?.id||null;state.log=[count>1?`<b>${count} enemies</b> close in from opposite sides.`:`The <b>${m[0]}</b> blocks your path.`];state.evade=false;state.boost=0;state.boostPower=3;state.exhausted=new Set();state.echoUsed=false;state.animating=true;state.fx=null;state.sceneEntering=true;state.encounterIntro=true;state.cardsArriving=false;if(activeEcho()&&state.echoMode==='recruit')applyRecruitedEcho();let reducedMotion=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;encounterIntroTimer=setTimeout(()=>finishEncounterIntro(false),reducedMotion?60:encounterIntroDuration());render();}
function pluralEnemy(name){if(name.endsWith('Wretch'))return name.replace(/Wretch$/,'Wretches');if(name.endsWith('s'))return name;return `${name}s`;}
function encounterIntroDuration(){return state.encounterType==='Boss'?5000:state.encounterType==='Elite'?4200:3600;}
function encounterChoreography(){let sets=[
 [{x:27,bottom:1,entry:'-18vw',delay:0,mirror:1},{x:73,bottom:3,entry:'18vw',delay:.18,mirror:-1}],
 [{x:18,bottom:4,entry:'-22vw',delay:.04,mirror:1},{x:50,bottom:8,entry:'0vw',delay:.28,mirror:-1},{x:82,bottom:4,entry:'22vw',delay:.12,mirror:-1}],
 [{x:34,bottom:0,entry:'-10vw',delay:.06,mirror:1},{x:66,bottom:2,entry:'10vw',delay:.24,mirror:-1}],
 [{x:50,bottom:-12,entry:'0vw',delay:.12,mirror:1}],
 [{x:50,bottom:-14,entry:'0vw',delay:.28,mirror:1}]
 ];return sets[state.level]||state.enemies.map((_,i)=>({x:50,entry:'0vw',bottom:0,delay:i*.16,mirror:i%2?-1:1}));}
function encounterReveal(){let count=state.enemies.length,choreography=encounterChoreography(),title=count===1?`${state.encounterName} emerges`:`${pluralEnemy(state.encounterName)} emerge`,kind=state.encounterType.toLowerCase(),threat=kind==='boss'?'A sovereign stirs':kind==='elite'?'An elite guardian rises':'Ambush',cutout=state.scene?.cutout;return `<section class="encounter-reveal ${kind} count-${count}" aria-label="${title}"><div class="reveal-vignette"></div><div class="reveal-fog fog-one"></div><div class="reveal-fog fog-two"></div>${kind==='boss'?'<div class="boss-omen"><i></i><i></i><i></i></div>':''}${state.enemies.map((e,i)=>{let c=choreography[i]||{x:50,bottom:0,entry:'0vw',delay:i*.16,mirror:i%2?-1:1},style=`--reveal-x:${c.x}%;--reveal-bottom:${c.bottom}vh;--entry-x:${c.entry};--reveal-delay:${c.delay}s;--reveal-mirror:${c.mirror};view-transition-name:enemy-reveal-${i}`,cinematicArt=cutout||e.art;return cinematicArt?`<div class="reveal-creature ${cutout?'is-cutout':''}" style="${style}"><span class="creature-shadow"></span><img src="${cinematicArt}" alt="" /></div>`:`<div class="reveal-symbol" style="${style}">${e.icon}</div>`}).join('')}<div class="reveal-copy"><div class="reveal-threat">${threat} · Fight ${state.level+1} of 5</div><div class="scene-kicker">${state.scene?.name||WORLDS[state.world].name}</div><h2>${title}</h2><p>${state.scene?.intro||'Something moves beyond the edge of sight.'}</p></div><div class="card-forming" aria-hidden="true">The encounter takes shape</div><button class="skip-intro" onclick="skipEncounterIntro()">Skip encounter</button></section>`;}
function commitEncounterCards(){state.encounterIntro=false;state.sceneEntering=false;state.cardsArriving=true;state.animating=false;render();setTimeout(()=>state.cardsArriving=false,1050);}
function finishEncounterIntro(skipped=false){if(!state.encounterIntro)return;if(encounterIntroTimer){clearTimeout(encounterIntroTimer);encounterIntroTimer=null;}let reducedMotion=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches,canMorph=!skipped&&!reducedMotion&&typeof document.startViewTransition==='function';if(canMorph){document.documentElement.classList.add('encounter-morphing',`morph-${state.encounterType.toLowerCase()}`);let transition=document.startViewTransition(commitEncounterCards);transition.finished.finally(()=>document.documentElement.classList.remove('encounter-morphing','morph-normal','morph-elite','morph-boss'));}else commitEncounterCards();}
function skipEncounterIntro(){finishEncounterIntro(true);}
function sceneAmbience(){if(state.world!==0||!state.scene)return '';if(state.level===0){let leaves=Array.from({length:16},(_,i)=>`<i class="wind-leaf" style="--leaf-y:${14+(i*19)%68}%;--leaf-size:${5+(i%4)*2}px;--leaf-delay:${-(i*.83)}s;--leaf-time:${8+(i%5)*1.35}s;--leaf-drift:${-8+(i%5)*4}vh"></i>`).join('');return `<div class="scene-ambience threshold-wind" aria-hidden="true"><span class="cold-gust gust-a"></span><span class="cold-gust gust-b"></span>${leaves}</div>`;}if(state.level===1)return `<div class="scene-ambience hunter-stalk" aria-hidden="true"><span class="ground-fog fog-back"></span><span class="wolf-shadow wolf-left"><img src="assets/enemies/cinematic/briar-hound-cutout.webp" alt="" /></span><span class="wolf-shadow wolf-right"><img src="assets/enemies/cinematic/briar-hound-cutout.webp" alt="" /></span><span class="forest-edge edge-left"></span><span class="forest-edge edge-right"></span><span class="ground-fog fog-middle"></span><span class="ground-fog fog-front"></span></div>`;if(state.level===2){let spores=Array.from({length:18},(_,i)=>`<i class="spore-mote" style="--mote-x:${7+(i*29)%88}%;--mote-size:${2+(i%4)*1.4}px;--mote-delay:${-(i*.71)}s;--mote-time:${8+(i%6)*1.4}s;--mote-sway:${-35+(i%7)*12}px"></i>`).join('');return `<div class="scene-ambience fungal-spores" aria-hidden="true"><span class="hollow-glow"></span>${spores}</div>`;}if(state.level===3){let debris=Array.from({length:14},(_,i)=>`<i class="grove-debris" style="--debris-x:${5+(i*23)%92}%;--debris-size:${2+(i%4)*1.5}px;--debris-delay:${-(i*.92)}s;--debris-time:${7+(i%5)*1.6}s"></i>`).join('');return `<div class="scene-ambience broken-grove" aria-hidden="true"><span class="shrine-dust"></span>${debris}</div>`;}let wisps=Array.from({length:16},(_,i)=>`<i class="root-wisp" style="--wisp-x:${12+(i*31)%78}%;--wisp-size:${2+(i%3)*1.5}px;--wisp-delay:${-(i*.8)}s;--wisp-time:${7+(i%5)*1.2}s;--wisp-sway:${-26+(i%6)*11}px"></i>`).join('');return `<div class="scene-ambience heartroot-energy" aria-hidden="true"><span class="throne-pulse"></span>${wisps}</div>`;}
function echoSupportCard(){let e=activeEcho();if(!e)return '';let recruited=state.echoMode==='recruit',disabled=state.animating||state.echoUsed||!currentTarget();if(recruited)return `<aside class="echo-support recruited"><span>Recruited Echo</span><b>${e.icon} ${e.name} · ${e.ability.name}</b><small>Rank ${e.ability.rank||1} · triggers at half strength each fight</small></aside>`;return `<button class="echo-support summon ${state.echoUsed?'spent':''}" onclick="summonEcho()" ${disabled?'disabled':''}><span>Summon Echo</span><b>${e.icon} ${e.name} · ${e.ability.name}</b><small>${state.echoUsed?'Spent this fight':`Rank ${e.ability.rank||1} · full strength · free action`}</small></button>`;}
function game(){let w=WORLDS[state.world];let active=state.party[state.turn%state.party.length];if(active?.currentHp<=0)active=nextLiving();let inspected=state.party.find(h=>h.id===state.inspectedHeroId)||active,isActing=inspected?.id===active?.id;app.innerHTML=`<div class="combat-screen ${state.encounterType.toLowerCase()} ${state.sceneEntering?'scene-entering':''} ${state.encounterIntro?'encounter-cinematic':''} ${state.cardsArriving?'cards-arriving':''} ${state.fx?.kind==='enemy'?'enemy-retaliating':''}" ${state.scene?`style="--scene:url('${state.scene.bg}')"`:''}><div class="combat-shade"></div>${sceneAmbience()}${state.encounterIntro?encounterReveal():''}<header class="combat-hud"><div class="combat-topbar">${topbar()}</div><section class="world-strip"><div class="world-title"><div class="world-number">0${state.world+1}</div><div><div class="eyebrow" style="color:${w.color}">${w.tone}</div><h3>${w.name}</h3></div></div><div class="path">${[0,1,2,3,4].map((n,i)=>`${i?'<span class="dash"></span>':''}<span class="node ${i<state.level?'done':i===state.level?'active':''} ${i===3?'elite-node':''}">${i===4?'♛':i===3?'◆':i+1}</span>`).join('')}</div></section></header><main class="battlefield">${echoSupportCard()}${state.scene?`<section class="scene-story"><div class="scene-kicker">${state.scene.name}</div><p>${state.scene.intro}</p></section>`:''}<section class="enemy-stage count-${state.enemies.length}"><div class="encounter-label ${state.encounterType.toLowerCase()}">${state.encounterType} · Fight ${state.level+1} of 5</div><div class="enemy-zone">${state.enemies.map(enemyCard).join('')}</div></section><section class="command-deck"><div class="action-tray"><div class="action-heading"><div><span>${isActing?'Ready to act':'Viewing loadout'}</span><strong>${inspected?.name||''}</strong></div>${!isActing&&active?`<button class="return-turn" onclick="inspectHero('${active.id}')">Return to ${active.name}</button>`:`<small>Choose an ability, then strike your target</small>`}</div><div class="abilities">${inspected?inspected.abilities.map((a,i)=>`<button class="ability-btn ${state.fx?.abilityName===a.name?'ability-cast':''}" title="${abilityText(a)}" ${state.animating||!isActing||state.exhausted.has(a.name)||inspected.currentHp<=0?'disabled':''} onclick="useAbility('${inspected.id}',${i})"><span class="ability-icon">${a.icon||'✦'}</span><span class="ability-name">${a.name}</span><span class="ability-rank">R${a.rank||1}</span><span class="ability-tooltip">${abilityText(a)}</span></button>`).join(''):''}</div></div><div class="hero-deck">${state.party.map(h=>memberCard(h,active,inspected)).join('')}</div><div class="combat-log"><span>Battle log</span>${state.log.slice(-3).join('<br>')}</div></section></main></div>`;}
function inspectHero(id){if(state.party.some(h=>h.id===id)){state.inspectedHeroId=id;render();}}
function jumpEncounter(delta){if(state.screen!=='game'||state.encounterIntro)return;let next=Math.max(0,Math.min(4,state.level+delta));if(next===state.level)return;document.querySelector('#modal')?.remove();state.level=next;state.party.forEach(h=>h.currentHp=h.maxHp);startEncounter();}
function heroAbilitySlots(h,active,dead){return Array.from({length:4},(_,i)=>{let a=h.abilities[i];if(!a)return `<span class="hero-ability-empty"><span>◇</span><small>Empty</small></span>`;let canUse=active?.id===h.id&&!state.animating&&!dead&&!state.exhausted.has(a.name),click=canUse?`useAbility('${h.id}',${i})`:(!state.animating&&!dead?`inspectHero('${h.id}')`:``);return `<button type="button" class="hero-ability-btn ${canUse?'can-use':'locked'} ${state.fx?.abilityName===a.name&&state.fx?.heroId===h.id?'ability-cast':''}" title="${abilityText(a)}" aria-label="${a.name}, rank ${a.rank||1}. ${abilityText(a)}" onclick="event.stopPropagation();${click}"><span class="hero-ability-icon">${a.icon||'✦'}</span><span class="hero-ability-name">${a.name}</span><span class="hero-ability-rank">R${a.rank||1}</span><span class="ability-tooltip">${abilityText(a)}</span></button>`}).join('');}
function memberCard(h,active,inspected){let pct=Math.max(0,h.currentHp/h.maxHp*100),shownHp=Math.max(0,h.currentHp),dead=h.currentHp<=0,locked=dead||state.animating,healFx=(state.fx?.heals||[]).filter(x=>x.heroId===h.id).reduce((sum,x)=>sum+x.amount,0),damageFx=state.fx?.heroDamage?.heroId===h.id?state.fx.heroDamage.amount:0,evaded=state.fx?.evadedHeroId===h.id;return `<article class="battle-hero-card ${active?.id===h.id?'active-turn':''} ${inspected?.id===h.id?'inspected':''} ${dead?'fallen':''} ${locked?'hero-locked':''} ${state.fx?.heroId===h.id?'hero-strike':''} ${damageFx?'hero-hit':''} ${healFx?'hero-healed':''}" ${locked?'':`onclick="inspectHero('${h.id}')"`} aria-label="${h.name}, ${shownHp} of ${h.maxHp} health">${damageFx?`<span class="combat-number damage-number">-${damageFx}</span>`:''}${healFx?`<span class="combat-number heal-number">+${healFx}</span>`:''}${evaded?`<span class="combat-number evade-number">Evade</span>`:''}<div class="battle-hero-art">${h.art?`<img src="${h.art}" alt="${h.name}" />`:h.icon}</div><div class="battle-hero-copy"><div class="class">${active?.id===h.id?'Current turn':h.role}</div><h3>${h.name}</h3><div class="hp-row"><div class="bar"><span style="width:${pct}%"></span></div><b>${shownHp}</b><small>/${h.maxHp}</small></div></div><div class="hero-abilities" aria-label="${h.name}'s abilities">${heroAbilitySlots(h,active,dead)}</div></article>`;}
function enemyCard(e,i){let pct=Math.max(0,e.hp/e.maxHp*100),dead=e.hp<=0,damageFx=(state.fx?.enemyDamage||[]).filter(x=>x.index===i).reduce((sum,x)=>sum+x.amount,0),hit=state.fx?.hitTargets?.includes(i),defeated=state.fx?.defeated?.includes(i);return `<button class="enemy-card enemy-select ${state.targetIndex===i&&!dead?'targeted':''} ${dead?'defeated':''} ${hit?'enemy-hit':''} ${state.fx?.enemyAttackerIndex===i?'enemy-strike':''} ${defeated?'just-defeated':''}" style="--enemy-index:${i};view-transition-name:enemy-reveal-${i}" onclick="selectTarget(${i})" ${dead||state.animating?'disabled':''}>${damageFx?`<span class="combat-number damage-number">-${damageFx}</span>`:''}${e.art?`<div class="enemy-portrait"><img class="${i%2?'mirrored':''}" src="${e.art}" alt="${e.name}" /></div>`:`<div class="enemy-art">${e.icon}</div>`}<div class="enemy-data"><div class="class">${dead?'Defeated':state.targetIndex===i?'Current target':state.encounterType}</div><h2>${e.name}</h2><div class="hp-row"><div class="bar enemy"><span style="width:${pct}%"></span></div><b>${Math.max(0,e.hp)}</b><small>/${e.maxHp}</small></div><div class="intent">${dead?'No longer acts':`⚔ ${e.damage}${e.weakened?' weakened':''}`}</div></div></button>`;}
function selectTarget(i){if(state.enemies[i]?.hp>0){state.targetIndex=i;render();}}
function currentTarget(){let target=state.enemies[state.targetIndex];if(!target||target.hp<=0){state.targetIndex=state.enemies.findIndex(e=>e.hp>0);target=state.enemies[state.targetIndex];}return target;}
function nextLiving(){return state.party.find(h=>h.currentHp>0);}
function lowest(){return [...state.party].filter(h=>h.currentHp>0).sort((a,b)=>a.currentHp/a.maxHp-b.currentHp/b.maxHp)[0];}
function heal(h,n){if(!h)return;let before=h.currentHp;h.currentHp=Math.min(h.maxHp,h.currentHp+n);let restored=Math.max(0,h.currentHp-before);if(restored&&state.fx?.kind==='hero')state.fx.heals.push({heroId:h.id,amount:restored});}
function hit(n,user){let target=currentTarget();if(!target)return;let index=state.enemies.indexOf(target),before=target.hp,bonus=target.expose+(state.boost>0?state.boostPower:0),total=n+bonus;target.hp-=total;if(state.fx){state.fx.enemyDamage.push({index,amount:total});if(!state.fx.hitTargets.includes(index))state.fx.hitTargets.push(index);if(before>0&&target.hp<=0&&!state.fx.defeated.includes(index))state.fx.defeated.push(index);}if(target.expose){state.log.push(`The exposed weakness adds <b>${target.expose}</b> damage.`);target.expose=0;}if(state.boost>0)state.boost--;state.log.push(`<b>${user.name}</b> deals ${total} damage to ${target.internalName||target.name}.`);}
function useAbility(id,index){let user=state.party.find(h=>h.id===id),active=state.party[state.turn%state.party.length],a=user?.abilities[index],target=currentTarget();if(state.animating||!user||!a||user.currentHp<=0||active?.id!==user.id||!target)return;state.animating=true;state.fx={kind:'hero',heroId:id,abilityName:a.name,enemyDamage:[],hitTargets:[],defeated:[],heals:[],heroDamage:null};
 if(a.type==='damage') hit(a.value+(a.execute&&target.hp<target.maxHp/2?a.execute:0),user);
 if(a.type==='hybrid'){hit(a.value,user);heal(lowest(),a.heal);state.log.push(`Restorative light heals an ally for <b>${a.heal}</b>.`)}
 if(a.type==='weaken'){hit(a.value,user);if(target.hp>0)target.weakened=Math.max(target.weakened,a.weaken||4);}
 if(a.type==='double'){hit(a.value,user);if(Math.random()<.45){hit(a.value,user);state.log.push('The second shot finds its mark!')}}
 if(a.type==='poison'){hit(a.value,user);if(target.hp>0)target.poison+=a.dot||3;}
 if(a.type==='evade'){hit(a.value,user);state.evade=true;}
 if(a.type==='pact'){user.currentHp-=3;state.fx.heroDamage={heroId:user.id,amount:3};hit(a.value,user);}
 if(a.type==='heal'){state.party.forEach(h=>heal(h,a.value));state.log.push(`<b>${user.name}</b> mends the party for ${a.value}.`)}
 if(a.type==='selfheal'){hit(a.value,user);heal(user,a.heal);}
 if(a.type==='expose'){hit(a.value,user);if(target.hp>0)target.expose=a.bonus||6;}
 if(a.type==='meteor'){hit(a.value,user);state.exhausted.add(a.name);}
 if(a.type==='cry'){hit(a.value,user);state.boost=2;state.boostPower=a.power||3;}
 if(state.enemies.every(e=>e.hp<=0)){render();setTimeout(victory,650);return;}currentTarget();render();setTimeout(enemyTurn,380);}
function enemyTurn(){state.fx={kind:'enemy',enemyDamage:[],hitTargets:[],defeated:[],heals:[],heroDamage:null,enemyAttackerIndex:null,evadedHeroId:null};state.enemies.filter(e=>e.hp>0&&e.poison).forEach(e=>{let index=state.enemies.indexOf(e),before=e.hp;e.hp-=e.poison;state.fx.enemyDamage.push({index,amount:e.poison});state.fx.hitTargets.push(index);if(before>0&&e.hp<=0)state.fx.defeated.push(index);state.log.push(`Poison deals <b>${e.poison}</b> damage to ${e.internalName||e.name}.`);});if(state.enemies.every(e=>e.hp<=0)){render();setTimeout(victory,600);return;}currentTarget();let livingEnemies=state.enemies.map((e,i)=>e.hp>0?i:-1).filter(i=>i>=0),attackerIndex=livingEnemies[state.enemyTurnIndex%livingEnemies.length],attacker=state.enemies[attackerIndex];state.enemyTurnIndex++;state.fx.enemyAttackerIndex=attackerIndex;
 let living=state.party.filter(h=>h.currentHp>0),victim=living[Math.floor(Math.random()*living.length)];if(state.evade){state.log.push(`<b>${victim.name}</b> slips through ${(attacker.internalName||attacker.name)}'s attack.`);state.fx.evadedHeroId=victim.id;state.evade=false;}else{let dmg=Math.max(1,attacker.damage-attacker.weakened);victim.currentHp-=dmg;state.fx.heroDamage={heroId:victim.id,amount:dmg};state.log.push(`${attacker.internalName||attacker.name} strikes <b>${victim.name}</b> for ${dmg}.`);attacker.weakened=0;}
 if(state.party.every(h=>h.currentHp<=0)){render();setTimeout(partyFell,600);return;}do{state.turn++}while(state.party[state.turn%state.party.length].currentHp<=0);state.inspectedHeroId=state.party[state.turn%state.party.length].id;render();setTimeout(()=>{state.animating=false;state.fx=null;render();},520);}
function rollRewards(){let rewards=[],used=new Set();for(let slot=0;slot<2;slot++){let fresh=REWARD_ABILITIES.filter(a=>!state.learnedAbilities.has(a.name)&&!used.has(a.name));let upgrades=state.party.flatMap(h=>h.abilities.map((a,index)=>({hero:h,ability:a,index}))).filter(x=>REWARD_ABILITY_NAMES.includes(x.ability.name)&&(x.ability.rank||1)<MAX_ABILITY_RANK&&!used.has(x.ability.name));let allowDuplicate=!rewards.some(r=>r.upgrade),takeDuplicate=upgrades.length&&(!fresh.length||(allowDuplicate&&Math.random()<DUPLICATE_CHANCE));if(takeDuplicate){let pick=upgrades[Math.floor(Math.random()*upgrades.length)],preview=rankPreview(pick.ability);rewards.push({...preview,upgrade:true,sourceName:pick.ability.name,targetHeroId:pick.hero.id,targetAbilityIndex:pick.index});used.add(pick.ability.name);}else if(fresh.length){let pick=fresh[Math.floor(Math.random()*fresh.length)];rewards.push({...pick,rank:1,desc:abilityText({...pick,rank:1})});used.add(pick.name);}else if(upgrades.length){let pick=upgrades[Math.floor(Math.random()*upgrades.length)],preview=rankPreview(pick.ability);rewards.push({...preview,upgrade:true,sourceName:pick.ability.name,targetHeroId:pick.hero.id,targetAbilityIndex:pick.index});used.add(pick.ability.name);}}return rewards;}
function victory(){if(state.screen!=='game'||state.enemies.some(e=>e.hp>0))return;state.animating=false;state.fx=null;if(state.level===4&&state.world===4){endGame();return;}state.rewards=rollRewards();state.assigned=0;state.pendingReplacement=null;showRewards();}
function rewardActions(a,i){if(a.given)return `<div class="assigned">✓ ${a.given}</div>`;if(a.upgrade){let h=state.party.find(x=>x.id===a.targetHeroId);return `<div class="rank-action"><button onclick="claimUpgrade(${i})">${h.icon} Rank up ${h.name}'s ${a.name}</button><small>No ability slot required</small></div>`;}let pending=state.pendingReplacement;if(pending?.rewardIndex===i){let h=state.party.find(x=>x.id===pending.heroId);return `<div class="replacement"><div class="replacement-title">${h.name} is full · replace one ability</div>${h.abilities.map((old,slot)=>{let locked=state.rewards.some(r=>r.upgrade&&!r.given&&r.targetHeroId===h.id&&r.sourceName===old.name);return `<button ${locked?'disabled':''} onclick="replaceAbility(${i},'${h.id}',${slot})"><span>${old.icon}</span><b>${old.name} · R${old.rank||1}</b><small>${locked?'Claim its pending rank first':`Replace with ${a.name}`}</small></button>`;}).join('')}<button class="cancel-swap" onclick="cancelReplacement()">Cancel replacement</button></div>`;}return `<div class="assign">${state.party.filter(h=>h.currentHp>0).map(h=>`<button onclick="assignReward(${i},'${h.id}')">${h.icon} ${h.name}${h.abilities.length>=4?' · Swap':' · '+h.abilities.length+'/4'}</button>`).join('')}</div>`;}
function showRewards(){let done=state.assigned===state.rewards.length,label=done?'Continue onward':state.assigned?'Continue without the other reward':'Continue without rewards';document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><section class="panel modal"><div class="eyebrow">Victory reward</div><h2>Two abilities survived</h2>${state.scene?.outro?`<div class="story-beat"><span>${state.scene.name}</span><p>${state.scene.outro}</p></div>`:''}<p>New abilities are most common. Uncommon duplicates rank up the equipped copy without using another slot. Every reward is optional.</p><div class="rewards">${state.rewards.map((a,i)=>`<div class="reward-card ${a.upgrade?'rank-reward':''} ${state.pendingReplacement?.rewardIndex===i?'swapping':''}"><div class="icon">${a.icon}</div><div class="reward-rank">${a.upgrade?`Rank up · R${a.rank}`:'New ability · R1'}</div><h3>${a.name}</h3><p>${abilityText(a)}</p>${rewardActions(a,i)}</div>`).join('')}</div><div class="reward-footer"><button class="primary" onclick="continueRun()">${label}</button>${done?'':`<small>Unclaimed rewards will be left behind.</small>`}</div></section></div>`)}
function claimUpgrade(i){let reward=state.rewards[i],h=state.party.find(x=>x.id===reward?.targetHeroId),a=h?.abilities.find(x=>x.name===reward?.sourceName);if(!reward||!reward.upgrade||reward.given||!a)return;rankUpAbility(a);reward.given=`${h.name}'s ${a.name} reached Rank ${a.rank}`;state.assigned++;document.querySelector('#modal').remove();showRewards();}
function assignReward(i,id){let a=state.rewards[i],h=state.party.find(x=>x.id===id);if(!a||a.upgrade||a.given||!h)return;if(h.abilities.length>=4){state.pendingReplacement={rewardIndex:i,heroId:id};document.querySelector('#modal').remove();showRewards();return;}h.abilities.push({...a,rank:1,desc:abilityText(a)});state.learnedAbilities.add(a.name);a.given=`Given to ${h.name}`;state.assigned++;state.pendingReplacement=null;document.querySelector('#modal').remove();showRewards();}
function replaceAbility(i,id,slot){let a=state.rewards[i],h=state.party.find(x=>x.id===id),old=h?.abilities[slot],locked=state.rewards.some(r=>r.upgrade&&!r.given&&r.targetHeroId===id&&r.sourceName===old?.name);if(!a||a.upgrade||a.given||!h||!old||locked)return;h.abilities.splice(slot,1,{...a,rank:1,desc:abilityText(a)});state.learnedAbilities.add(a.name);a.given=`Given to ${h.name} · replaced ${old.name}`;state.assigned++;state.pendingReplacement=null;document.querySelector('#modal').remove();showRewards();}
function cancelReplacement(){state.pendingReplacement=null;document.querySelector('#modal').remove();showRewards();}
function continueRun(){document.querySelector('#modal').remove();state.pendingReplacement=null;state.level++;if(state.level>4){state.world++;state.level=0;state.party.forEach(h=>h.currentHp=h.maxHp);state.log=[];}else state.party.forEach(h=>heal(h,8));startEncounter();}
function retainedAbility(h){return h.abilities.map((ability,index)=>({ability,index})).sort((a,b)=>(b.ability.rank||1)-(a.ability.rank||1)||b.index-a.index)[0]?.ability||h.start;}
function partyFell(){state.animating=false;state.fx=null;state.livesRemaining=Math.max(0,state.livesRemaining-1);state.pendingEchoOptions=state.party.map(h=>{let ability=retainedAbility(h);return {heroId:h.id,name:h.name,role:h.role,icon:h.icon,art:h.art,ability:{...ability,rank:ability.rank||1,desc:abilityText(ability)}};});render();showDeath();}
function showDeath(){let final=state.livesRemaining===0;document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><section class="panel modal defeat-modal"><div class="eyebrow">Life lost · ${state.livesRemaining}/5 remain</div><h2 class="death-title">${final?'The fifth flame is extinguished':'Your expedition has fallen'}</h2><p>${final?'The cycle closes, but one final memory can still be bound.':'Choose one hero to leave behind as an Echo. Their highest-ranked ability—and its current rank—will survive the fall.'}</p><div class="death-echo-grid">${state.pendingEchoOptions.map(e=>`<button class="death-echo-card" onclick="forgeEcho('${e.heroId}')"><span class="death-echo-art">${e.art?`<img src="${e.art}" alt="${e.name}" />`:e.icon}</span><span class="class">${e.role}</span><b>${e.name}'s Echo</b><small>${e.ability.icon} ${e.ability.name} · Rank ${e.ability.rank||1}</small><em>Bind this memory</em></button>`).join('')}</div><div class="life-loss-row">${[0,1,2,3,4].map(i=>`<i class="life ${i>=state.livesRemaining?'lost':''}"></i>`).join('')}</div></section></div>`)}
function forgeEcho(heroId){let option=state.pendingEchoOptions.find(e=>e.heroId===heroId);if(!option)return;let echo={...option,id:`echo-${++state.echoSerial}`};state.echoes.push(echo);state.activeEchoId=echo.id;state.echoMode='summon';state.learnedAbilities.add(echo.ability.name);state.pendingEchoOptions=[];document.querySelector('#modal')?.remove();if(state.livesRemaining<=0){showFinalDefeat(echo);return;}reformParty();}
function reformParty(){state.level=0;state.selected=[];state.screen='select';state.party=[];state.rewards=[];state.pendingReplacement=null;render();}
function showFinalDefeat(echo){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><section class="panel modal final-defeat"><div class="eyebrow">No lives remain</div><h2 class="death-title">The campaign becomes an echo</h2><p>${echo.name}'s <b>${echo.ability.name}</b> survived at Rank ${echo.ability.rank||1}, but there is no living party left to carry it.</p><div class="final-echo">${echo.icon} ${echo.name}'s Echo · ${echo.ability.icon} ${echo.ability.name} R${echo.ability.rank||1}</div><button class="primary" onclick="location.reload()">Begin a new cycle</button></section></div>`)}
function castEchoEffect(e,multiplier=1,allowKill=false){let a=e.ability,target=currentTarget(),damage=Math.max(0,Math.floor((a.value||0)*multiplier)),restored=0,dealt=0;if(a.type==='heal'){let amount=Math.max(1,damage);state.party.filter(h=>h.currentHp>0).forEach(h=>{let before=h.currentHp;heal(h,amount);restored+=h.currentHp-before;});state.log.push(`<b>${e.name}'s Echo</b> restores ${restored} party health with ${a.name}.`);return;}if(target&&damage){let index=state.enemies.indexOf(target),before=target.hp;target.hp=allowKill?target.hp-damage:Math.max(1,target.hp-damage);dealt=before-target.hp;if(state.fx){state.fx.enemyDamage.push({index,amount:dealt});state.fx.hitTargets.push(index);if(before>0&&target.hp<=0)state.fx.defeated.push(index);}}if(a.heal){let amount=Math.max(1,Math.floor(a.heal*multiplier)),wounded=lowest(),before=wounded?.currentHp||0;heal(wounded,amount);restored=(wounded?.currentHp||0)-before;}if(multiplier>=1&&target?.hp>0){if(a.type==='poison')target.poison+=a.dot||3;if(a.type==='weaken')target.weakened=Math.max(target.weakened,a.weaken||4);if(a.type==='expose')target.expose=Math.max(target.expose,a.bonus||6);if(a.type==='evade')state.evade=true;if(a.type==='cry'){state.boost=2;state.boostPower=a.power||3;}}state.log.push(`<b>${e.name}'s Echo</b> casts ${a.name}${dealt?` for ${dealt} damage`:''}${restored?` and restores ${restored} health`:''}.`);}
function applyRecruitedEcho(){let e=activeEcho();if(e)castEchoEffect(e,.5,false);}
function summonEcho(){let e=activeEcho();if(!e||state.echoMode!=='summon'||state.echoUsed||state.animating||!currentTarget())return;state.echoUsed=true;state.animating=true;state.fx={kind:'hero',heroId:'echo',abilityName:e.ability.name,enemyDamage:[],hitTargets:[],defeated:[],heals:[],heroDamage:null};castEchoEffect(e,1,true);render();if(state.enemies.every(enemy=>enemy.hp<=0)){setTimeout(victory,650);return;}setTimeout(()=>{state.animating=false;state.fx=null;render();},560);}
function endGame(){document.body.insertAdjacentHTML('beforeend',`<div class="overlay"><section class="panel modal"><div class="eyebrow">The cycle is broken</div><h2>Five worlds remember your name</h2><p>You defeated the End of Five with ${state.livesRemaining} lives and ${state.echoes.length} ${state.echoes.length===1?'Echo':'Echoes'} remaining in the archive.</p><button class="primary" onclick="location.reload()">Play another cycle</button></section></div>`)}
render();
