const HEROES = [
  { id:'rogue', name:'Nyx', role:'Rogue', icon:'🗡️', art:'assets/heroes/nyx-rogue.webp', hp:24, passive:'Opportunist', passiveDesc:'All attacks deal +2 damage to enemies below half health.', start:{name:'Backstab', icon:'🗡️', desc:'Deal 8 damage. +4 if the enemy is below half health.', type:'damage', value:8, execute:4} },
  { id:'guardian', name:'Bram', role:'Guardian', icon:'🛡️', art:'assets/heroes/bram-guardian.webp', hp:34, passive:'Steadfast', passiveDesc:'The first hit each encounter deals 3 less damage.', passiveOnce:true, start:{name:'Protect', icon:'🛡️', desc:'Deal 4 damage and restore 5 party health.', type:'hybrid', value:4, heal:5} },
  { id:'witch', name:'Mora', role:'Veilborn Witch', icon:'🔮', art:'assets/heroes/mora-veilborn-warlock-v2.webp', hp:22, passive:'Lingering Curse', passiveDesc:'Weaken reduces 2 additional damage and poison gains +1.', start:{name:'Hex', icon:'🕸️', desc:'Deal 6 damage and weaken the next enemy attack.', type:'weaken', value:6} },
  { id:'ranger', name:'Ash', role:'Ranger', icon:'🏹', art:'assets/heroes/ash-ranger.webp', hp:26, passive:'Keen Eye', passiveDesc:'The first damaging action each encounter deals +4 damage.', passiveOnce:true, start:{name:'Twin Shot', icon:'🏹', desc:'Deal 7 damage with a chance to strike twice.', type:'double', value:7} },
  { id:'cleric', name:'Sol', role:'Cleric', icon:'☀️', art:'assets/heroes/sol-cleric.webp', hp:28, passive:'Last Light', passiveDesc:'Once each encounter, prevent a hero from falling and leave them at 1 health.', passiveOnce:true, start:{name:'Radiance', icon:'☀️', desc:'Deal 5 damage and heal the most wounded hero for 7.', type:'hybrid', value:5, heal:7} }
];

const ABILITIES = [
 {name:'Poisoned Edge',icon:'🧪',desc:'Deal 6 damage now and 3 after every enemy turn.',type:'poison',value:6},
 {name:'Shadowstep',icon:'🌘',desc:'Deal 7 damage and evade the next enemy attack.',type:'evade',value:7,cooldown:1},
 {name:'Blood Pact',icon:'🩸',desc:'Lose 3 health to deal 14 damage.',type:'pact',value:14},
 {name:'Chain Lightning',icon:'⚡',desc:'Deal 10 damage. Strong, simple, reliable.',type:'damage',value:10},
 {name:'Mend Fate',icon:'🧵',desc:'Heal the entire party for 6.',type:'heal',value:6},
 {name:'Vanguard',icon:'⚔️',desc:'Deal 5 damage and restore 8 health to yourself.',type:'selfheal',value:5,heal:8},
 {name:'Expose',icon:'👁️',desc:'Deal 5 damage; the next hero deals +6.',type:'expose',value:5},
 {name:'Soul Siphon',icon:'🕯️',desc:'Deal 7 damage and heal the most wounded hero for 5.',type:'hybrid',value:7,heal:5},
 {name:'Meteor',icon:'☄️',desc:'Deal 16 damage, then this ability becomes exhausted.',type:'meteor',value:16},
 {name:'Battle Cry',icon:'📯',desc:'Deal 4 damage and empower the next two attacks by 3.',type:'cry',value:4},
 {name:'Silent Cut',icon:'🤫',desc:'Deal 9 damage before the enemy can react.',type:'damage',value:9},
 {name:'Smoke Veil',icon:'💨',desc:'Deal 5 damage and evade the next enemy attack.',type:'evade',value:5,cooldown:1},
 {name:'Purifying Wave',icon:'💧',desc:'Heal the entire party for 5.',type:'heal',value:5},
 {name:'Iron Resolve',icon:'⛓️',desc:'Deal 4 damage and restore 10 health to yourself.',type:'selfheal',value:4,heal:10},
 {name:'Mark Prey',icon:'🎯',desc:'Deal 4 damage; the next hero deals +6.',type:'expose',value:4},
 {name:'Venom Bloom',icon:'🐍',desc:'Deal 5 damage now and 3 after every enemy turn.',type:'poison',value:5},
 {name:'Dark Bargain',icon:'🫀',desc:'Lose 3 health to deal 13 damage.',type:'pact',value:13},
 {name:'Thunderclap',icon:'🌩️',desc:'Deal 7 damage and weaken the next enemy attack.',type:'weaken',value:7},
 {name:'Lifebloom',icon:'🌺',desc:'Deal 4 damage and heal the most wounded hero for 8.',type:'hybrid',value:4,heal:8},
 {name:'Falling Star',icon:'🌠',desc:'Deal 15 damage, then this ability becomes exhausted.',type:'meteor',value:15},
 {name:'War Drums',icon:'🥁',desc:'Deal 3 damage and empower the next two attacks by 3.',type:'cry',value:3},
 {name:"Executioner's Arc",icon:'🪓',desc:'Deal 12 heavy damage.',type:'damage',value:12},
 {name:'Phase Lance',icon:'🌀',desc:'Deal 8 damage and evade the next enemy attack.',type:'evade',value:8,cooldown:1},
 {name:'Rejuvenating Rain',icon:'🌧️',desc:'Heal the entire party for 5.',type:'heal',value:5},
 {name:'Leeching Brand',icon:'🦷',desc:'Deal 8 damage and heal the most wounded hero for 4.',type:'hybrid',value:8,heal:4},
 {name:'Crippling Shot',icon:'🪶',desc:'Deal 8 damage and weaken the next enemy attack.',type:'weaken',value:8},
 {name:'Oathbreaker',icon:'⚔️',desc:'Deal 6 damage with a chance to strike twice.',type:'double',value:6},
 {name:'Ember Ward',icon:'🕯️',desc:'Deal 6 damage and restore 6 health to yourself.',type:'selfheal',value:6,heal:6},
 {name:'Death Mark',icon:'☠️',desc:'Deal 6 damage; the next hero deals +6.',type:'expose',value:6},
 {name:'Serpent Strike',icon:'🐉',desc:'Deal 7 damage now and 3 after every enemy turn.',type:'poison',value:7},
 {name:'Grave Needle',icon:'🪡',desc:'Deal 9 precise damage.',type:'damage',value:9},
 {name:'Aegis Pulse',icon:'🔆',desc:'Deal 5 damage and heal the most wounded hero for 6.',type:'hybrid',value:5,heal:6},
 {name:'Witchfire',icon:'🟣',desc:'Deal 9 damage and weaken the next enemy attack.',type:'weaken',value:9},
 {name:'Moon Salve',icon:'🌙',desc:'Heal the entire party for 7.',type:'heal',value:7},
 {name:'Razorwind',icon:'🌪️',desc:'Deal 8 damage with a chance to strike twice.',type:'double',value:8},
 {name:'Phantom Guard',icon:'👤',desc:'Deal 6 damage and evade the next enemy attack.',type:'evade',value:6,cooldown:1},
 {name:'Ruinous Oath',icon:'📜',desc:'Lose 3 health to deal 15 damage.',type:'pact',value:15},
 {name:'Rotfang',icon:'🦠',desc:'Deal 8 damage now and 3 after every enemy turn.',type:'poison',value:8},
 {name:'Sun Spear',icon:'🌞',desc:'Deal 11 radiant damage.',type:'damage',value:11},
 {name:'Mercy Chain',icon:'⛓️',desc:'Deal 6 damage and heal the most wounded hero for 7.',type:'hybrid',value:6,heal:7},
 {name:"Predator's Mark",icon:'🐾',desc:'Deal 7 damage; the next hero deals +6.',type:'expose',value:7},
 {name:'Stoneblood',icon:'🪨',desc:'Deal 7 damage and restore 9 health to yourself.',type:'selfheal',value:7,heal:9},
 {name:'Veil Collapse',icon:'🕳️',desc:'Deal 17 damage, then this ability becomes exhausted.',type:'meteor',value:17},
 {name:'Marching Hymn',icon:'🎺',desc:'Deal 5 damage and empower the next two attacks by 3.',type:'cry',value:5},
 {name:'Dusk Bolt',icon:'🌆',desc:'Deal 10 shadow damage.',type:'damage',value:10},
 {name:'Thornskin',icon:'🌵',desc:'Deal 5 damage and restore 11 health to yourself.',type:'selfheal',value:5,heal:11},
 {name:'Blinding Ash',icon:'🌫️',desc:'Deal 6 damage and weaken the next enemy attack.',type:'weaken',value:6},
 {name:'Night Venom',icon:'🦂',desc:'Deal 6 damage now and 3 after every enemy turn.',type:'poison',value:6},
 {name:'Silver Volley',icon:'🪶',desc:'Deal 7 damage with a chance to strike twice.',type:'double',value:7},
 {name:'Fate Rend',icon:'✂️',desc:'Deal 8 damage; the next hero deals +6.',type:'expose',value:8}
];

const REWARD_ABILITY_NAMES = ['Poisoned Edge','Shadowstep','Blood Pact','Chain Lightning','Mend Fate','Vanguard','Expose','Soul Siphon','Meteor','Battle Cry','Thunderclap','Oathbreaker'];
const REWARD_ABILITIES = REWARD_ABILITY_NAMES.map(name=>ABILITIES.find(a=>a.name===name));
const MAX_ABILITY_RANK = 5;
const DUPLICATE_CHANCE = .18;
const MAX_EQUIPPED_ECHOES = 3;
const SHOP_ITEMS = [
 {id:'damage',name:'Sharpened Sigil',icon:'⚔️',price:25,tier:'Small item',effect:'+2 team damage',desc:'Etch a keen echo into every weapon. All hero attacks deal +2 damage during the coming boss fight.'},
 {id:'defense',name:'Warding Charm',icon:'🛡️',price:25,tier:'Small item',effect:'−2 damage taken',desc:'Bind a protective echo to the party. Every incoming hit deals 2 less damage during the coming boss fight.'},
 {id:'heal',name:'Hearth Tonic',icon:'🧪',price:25,tier:'Small item',effect:'Full party heal',desc:'A flask of bottled campfire warmth. Restore every surviving hero to full health immediately.'},
 {id:'revive',name:'Phoenix Thread',icon:'🔥',price:50,tier:'Major relic',effect:'Revive at full health',desc:'Stitch one fallen hero back into the living world at full health. A costly answer when the road claims an ally.'}
];

function abilityText(a){let dot=a.dot||3,weaken=a.weaken||4,bonus=a.bonus||6,power=a.power||3;if(a.type==='damage')return `Deal ${a.value} damage${a.execute?`. +${a.execute} below half health.`:'.'}`;if(a.type==='hybrid')return `Deal ${a.value} damage and heal the most wounded hero for ${a.heal}.`;if(a.type==='weaken')return `Deal ${a.value} damage and reduce the next enemy attack by ${weaken}.`;if(a.type==='double')return `Deal ${a.value} damage with a 45% chance to strike twice.`;if(a.type==='poison')return `Deal ${a.value} damage and add ${dot} poison after every enemy turn.`;if(a.type==='evade')return `Deal ${a.value} damage and evade the next enemy attack.${a.cooldown?' Cooldown: 1 hero turn.':''}`;if(a.type==='pact')return `Lose 3 health to deal ${a.value} damage.`;if(a.type==='heal')return `Heal the entire party for ${a.value}.`;if(a.type==='selfheal')return `Deal ${a.value} damage and restore ${a.heal} health to yourself.`;if(a.type==='expose')return `Deal ${a.value} damage; the next hero deals +${bonus}.`;if(a.type==='meteor')return `Deal ${a.value} damage, then this ability becomes exhausted.`;if(a.type==='cry')return `Deal ${a.value} damage and empower the next two attacks by ${power}.`;return a.desc;}
function cooldownSlot(abilityName){return ABILITIES.find(a=>a.name===abilityName)?.type==='evade'?'full-evade':abilityName;}
function cooldownKey(heroId,abilityName){return `${heroId}::${cooldownSlot(abilityName)}`;}
function abilityCooldown(heroId,abilityName){return state.cooldowns?.[cooldownKey(heroId,abilityName)]||0;}
function setAbilityCooldown(heroId,abilityName,turns){if(turns>0)state.cooldowns[cooldownKey(heroId,abilityName)]=turns;}
function tickHeroCooldowns(heroId){Object.keys(state.cooldowns).forEach(key=>{if(!key.startsWith(`${heroId}::`))return;state.cooldowns[key]--;if(state.cooldowns[key]<=0)delete state.cooldowns[key];});}
function rankUpAbility(a){a.rank=Math.min(MAX_ABILITY_RANK,(a.rank||1)+1);let gain=a.type==='meteor'?3:['damage','pact'].includes(a.type)?2:1;if(typeof a.value==='number')a.value+=gain;if(a.heal)a.heal+=2;if(a.type==='poison')a.dot=(a.dot||3)+1;if(a.type==='weaken')a.weaken=(a.weaken||4)+1;if(a.type==='expose')a.bonus=(a.bonus||6)+2;if(a.type==='cry')a.power=(a.power||3)+1;a.desc=abilityText(a);return a;}
function rankPreview(a){return rankUpAbility({...a});}

const WORLDS = [
 {name:'The Verdant Oath',tone:'Before the kingdom fell',color:'#70c69b',mobs:[
  ['Thorn Wretch','🌿',18,4,'assets/enemies/thorn-wretch.webp',2,'Normal',{name:'The Forest Threshold',bg:'assets/scenes/verdant-1-threshold.webp',cutout:'assets/enemies/cinematic/thorn-wretch-cutout.webp',intro:'The old road ends beneath a wall of ancient trees. Two figures tear themselves free from the thorn-choked verge.',outro:'The Wretches collapse into lifeless roots. Beyond them, a narrow trail winds beneath the canopy—and something deeper in the forest begins to howl.'},{pattern:'regrow'}],
  ['Briar Hound','🐺',18,5,'assets/enemies/briar-hound.webp',3,'Normal',{name:"The Hunter's Trail",bg:'assets/scenes/verdant-2-trail.webp',cutout:'assets/enemies/cinematic/briar-hound-cutout.webp',intro:'The canopy swallows the last daylight. Claw marks score the trunks, and three Briar Hounds circle the party through the mist.',outro:'The Briar Hound pack falls silent. Their tracks lead deeper, toward a hollow where violet spores drift between the trees.'},{pattern:'pack'}],
  ['Spore Stalker','🍄',24,6,'assets/enemies/spore-stalker.webp',2,'Normal',{name:'The Fungal Hollow',bg:'assets/scenes/verdant-3-hollow.webp',cutout:'assets/enemies/cinematic/spore-stalker-cutout.webp',intro:'The trail dissolves into black water and luminous fungus. Two tall shapes unfold beneath pale mushroom crowns.',outro:'The Stalkers burst into clouds of dying spores. Through the clearing, broken shrine stones point toward the forest’s oldest path.'},{pattern:'spores'}],
  ['Mossbound Ogre','🧌',58,9,'assets/enemies/mossbound-ogre.webp',1,'Elite',{name:'The Broken Grove',bg:'assets/scenes/verdant-4-shrine.webp',cutout:'assets/enemies/cinematic/mossbound-ogre-cutout.webp',intro:'A ruined oath-shrine blocks the way. Its massive guardian rises from the altar, dragging a shattered pillar behind it.',outro:'The Ogre crashes through the ancient altar. Beneath the rubble, living roots twist into a staircase descending toward the heart of the forest.'},{pattern:'slam'}],
  ['The Root King','👑',78,11,'assets/enemies/root-king.webp',1,'Boss',{name:'The Heartroot Throne',bg:'assets/scenes/verdant-5-throne.webp',cutout:'assets/enemies/cinematic/root-king-cutout.webp',intro:'The forest opens into a cathedral of roots and black water. Upon the throne, an emerald gaze awakens beneath a crown of branches.',outro:'The Root King’s crown splits and the corruption recoils. For one breath, the forest remembers what it was before the worlds began to fall.'},{pattern:'drain'}]
 ]},
 {name:'The Ashen Wake',tone:'After the first flame died',color:'#e2824d',mobs:[
  ['Ember Imp','👹',18,5,'assets/enemies/ember-imp.webp',3,'Normal',{name:'The Burning Verge',bg:'assets/scenes/ashen-1-village-edge.webp',cutout:'assets/enemies/cinematic/ember-imp-cutout.webp',intro:'The party leaves the living woods behind and finds a village burning beneath a blackened sky. Three small shapes dance between the ruined homes.',outro:'The last Imp crumbles into sparks. Through the smoke, slow armoured footsteps answer from the village square.'},{burn:1,burnBurst:4,pattern:'kindle'}],
  ['Ash Revenant','💀',30,7,'assets/enemies/ash-revenant.webp',2,'Normal',{name:'The Ashen Square',bg:'assets/scenes/ashen-2-square.webp',cutout:'assets/enemies/cinematic/ash-revenant-cutout.webp',intro:'The town square is silent except for the bell tower. Two dead guards turn in perfect unison as Basilica sigils ignite inside their hollow chests.',outro:'The Revenants collapse, their command chains burning away. Every sigil points toward the road climbing to the Basilica.'},{burn:1,burnBurst:4,pattern:'guard'}],
  ['Flamebound Acolyte','⛓️',34,8,'assets/enemies/flamebound-acolyte.webp',2,'Normal',{name:'The Processional Road',bg:'assets/scenes/ashen-3-procession.webp',cutout:'assets/enemies/cinematic/flamebound-acolyte-cutout.webp',intro:'Ash lies knee-deep on the sacred road. Masked Acolytes swing their censers, calling the village dead toward the Last Flame.',outro:'The final censer splits open. Above, something enormous roars behind the Basilica doors and iron chains begin to snap.'},{burn:1,burnBurst:5,pattern:'rite'}],
  ['Cindermaw','🐅',76,11,'assets/enemies/cindermaw.webp',1,'Elite',{name:"The Saint's Courtyard",bg:'assets/scenes/ashen-4-courtyard.webp',cutout:'assets/enemies/cinematic/cindermaw-cutout.webp',intro:"Broken chains whip across the cathedral stones. The Pyre Saint's treasured beast stalks from its opened cage, molten stripes burning beneath black fur.",outro:'Cindermaw falls at the foot of the Basilica. The bronze doors open by themselves, revealing a single white flame within.'},{burn:1,burnBurst:6,pattern:'pounce'}],
  ['The Pyre Saint','🔥',104,11,'assets/enemies/pyre-saint.webp',1,'Boss',{name:'The Basilica of the Last Flame',bg:'assets/scenes/ashen-5-sanctum.webp',cutout:'assets/enemies/cinematic/pyre-saint-cutout.webp',intro:'At the end of the black nave, the Saint raises one hand. The Last Flame bends toward her, and every corpse in the village kneels.',outro:'The iron halo fractures. Fire races backward through the Basilica, freeing the dead from the Saint’s final command.'},{burn:1,burnBurst:7,pattern:'lastflame'}]
 ]},
 {name:'The Frozen Hour',tone:'Where time refuses to move',color:'#77b9dd',mobs:[['Glass Wraith','👻',48,9,null,1,'Normal'],['Rimefangs','🐺',28,6,null,2,'Normal'],['Frost Seer','🧙',60,11,null,1,'Normal'],['Frost Colossus','🗿',78,13,null,1,'Elite'],['The Pale Clock','🕰️',104,15,null,1,'Boss']]},
 {name:'The Hollow Court',tone:'A kingdom that remembers you',color:'#a783cf',mobs:[['Empty Knight','♞',58,11,null,1,'Normal'],['Whisper Shades','👤',32,7,null,2,'Normal'],['Grief Eater','🦇',72,13,null,1,'Normal'],['Mirror Champion','🪞',88,15,null,1,'Elite'],['The Echo Queen','👑',116,17,null,1,'Boss']]},
 {name:'The Fifth Reality',tone:'All your failures meet here',color:'#e4b66f',mobs:[['Worldless Choir','🎭',68,13,null,1,'Normal'],['Null Stalker','🕷️',76,14,null,1,'Normal'],['Fate Devourer','🐉',88,15,null,1,'Normal'],['Echo Tyrant','🜏',108,18,null,1,'Elite'],['The End of Five','🌑',140,20,null,1,'Boss']]}
];

let state = {screen:'title', selected:[], world:0, level:0, livesRemaining:5, shards:0, lastShardGain:0, rewardPaid:false, encounterType:'Normal', encounterName:'', scene:null, sceneEntering:false, encounterIntro:false, cardsArriving:false, party:[], enemies:[], targetIndex:0, enemyTurnIndex:0, enemyActionCount:0, intent:null, turn:0, inspectedHeroId:null, log:[], echoes:[], echoSerial:0, equippedEchoIds:[], echoUsed:false, pendingEchoOptions:[], rewards:[], assigned:0, pendingReplacement:null, learnedAbilities:new Set(), evade:null, boost:0, boostPower:3, pendingDamageBonus:0, pendingDefenseBonus:0, encounterDamageBonus:0, encounterDefenseBonus:0, shopOpen:false, shopBought:new Set(), cooldowns:{}, exhausted:new Set(), animating:false, fx:null};
const app = document.querySelector('#app');
let encounterIntroTimer=null;

function testNav(){if(state.screen!=='game')return '';let locked=state.animating||state.encounterIntro;return `<div class="test-nav" aria-label="Playtest campaign navigation"><span>Playtest</span><button onclick="jumpWorld(-1)" ${state.world===0||locked?'disabled':''} aria-label="Previous world">«</button><b>W${state.world+1}</b><button onclick="jumpWorld(1)" ${state.world===WORLDS.length-1||locked?'disabled':''} aria-label="Next world">»</button><i></i><button onclick="jumpEncounter(-1)" ${state.level===0||locked?'disabled':''} aria-label="Previous encounter">‹</button><b>${state.level+1}/5</b><button onclick="jumpEncounter(1)" ${state.level===4||locked?'disabled':''} aria-label="Next encounter">›</button></div>`;}
function topbar(){return `<div class="topbar"><div class="brand">FIFTH ECHO</div><div class="run-meta">${testNav()}<div class="shards" aria-label="${state.shards} echo shards"><span>✦</span><b>${state.shards}</b> shards</div><div class="lives" aria-label="${state.livesRemaining} of 5 lives remain"><span>Lives <b>${state.livesRemaining}/5</b></span>${[0,1,2,3,4].map(i=>`<i class="life ${i>=state.livesRemaining?'lost':''}"></i>`).join('')}</div></div></div>`}
function render(){ if(state.screen==='title') title(); else if(state.screen==='select') select(); else game(); }
function title(){ app.innerHTML=`<div class="shell">${topbar()}<section class="panel hero"><div class="eyebrow">A party-building roguelite</div><h1>Fifth<br>Echo</h1><p>Five lives. Five collapsing realities. Every fallen hero can return as an Echo—and every ability you give them may decide the final battle.</p><button class="primary" onclick="state.screen='select';render()">Begin the first world</button></section></div>`; }
function equippedEchoes(){return state.equippedEchoIds.map(id=>state.echoes.find(e=>e.id===id)).filter(Boolean);}
function echoKind(a){if(a.type==='heal'||a.heal)return 'Heal';if(['poison','weaken','expose','evade','cry'].includes(a.type))return 'Debuff';return 'Damage';}
function echoArchive(){if(!state.echoes.length)return '';let equipped=equippedEchoes();return `<section class="echo-archive panel"><div class="echo-archive-copy"><div class="eyebrow">The Echo Archive · ${equipped.length}/${MAX_EQUIPPED_ECHOES} equipped</div><h3>Build your support hand</h3><p>Equip up to three fallen Echoes. During each fight, choose <b>one</b> to cast—then the entire support hand is spent until the next encounter.</p></div><div class="echo-options">${state.echoes.map(e=>{let active=state.equippedEchoIds.includes(e.id),full=!active&&equipped.length>=MAX_EQUIPPED_ECHOES;return `<article class="echo-option ${active?'active':''}"><div class="echo-option-art">${e.art?`<img src="${e.art}" alt="${e.name}'s Echo" />`:e.icon}</div><div><span>${echoKind(e.ability)} · ${e.role} Echo</span><h4>${e.name}</h4><p>${e.ability.icon} ${e.ability.name} · R${e.ability.rank||1}</p></div><div class="echo-loadout-action"><button class="${active?'selected':''}" aria-pressed="${active}" ${full?'disabled':''} onclick="toggleEchoLoadout('${e.id}')">${active?'Unequip':full?'3/3 full':'Equip'}</button></div></article>`;}).join('')}</div></section>`;}
function toggleEchoLoadout(id){if(!state.echoes.some(e=>e.id===id))return;if(state.equippedEchoIds.includes(id))state.equippedEchoIds=state.equippedEchoIds.filter(echoId=>echoId!==id);else if(state.equippedEchoIds.length<MAX_EQUIPPED_ECHOES)state.equippedEchoIds.push(id);render();}
function select(){ app.innerHTML=`<div class="shell">${topbar()}<div class="section-head"><div><div class="eyebrow">Form your expedition</div><h2>Choose three heroes</h2><p>Each begins with one signature ability. Their next abilities are yours to shape.</p></div><div><b>${state.livesRemaining}</b> lives remain · ${state.selected.length} / 3 chosen</div></div>${echoArchive()}<div class="roster">${HEROES.map(h=>`<button class="hero-card ${h.art?'with-art':''} ${state.selected.includes(h.id)?'selected':''}" onclick="toggleHero('${h.id}')"><div class="portrait-stage">${h.art?`<img class="hero-art" src="${h.art}" alt="${h.name}, ${h.role}" />`:`<div class="portrait">${h.icon}</div>`}<span class="vitality">♥ ${h.hp}</span></div><div class="card-copy"><div class="class">${h.role}</div><h3>${h.name}</h3><div class="signature"><span>${h.start.name}</span><b>${h.start.icon}</b></div><p>${h.start.desc}</p><div class="passive" title="${h.passiveDesc}">${h.passive}<small>${h.passiveDesc}</small></div></div></button>`).join('')}</div><div class="action-row"><button class="primary" ${state.selected.length!==3?'disabled':''} onclick="begin()">${state.livesRemaining<5?`Return to ${WORLDS[state.world].name}`:'Enter the world'}</button></div></div>`; }
function toggleHero(id){ state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):(state.selected.length<3?[...state.selected,id]:state.selected); render(); }
function begin(){ state.party=state.selected.map(id=>{let h=HEROES.find(x=>x.id===id);return {...h,maxHp:h.hp,currentHp:h.hp,burn:0,passiveReady:true,abilities:[{...h.start,rank:1}]}});state.party.forEach(h=>h.abilities.forEach(a=>state.learnedAbilities.add(a.name)));state.screen='game';startEncounter(); }
function preloadEncounterAssets(...sources){if(typeof Image==='undefined')return;sources.filter(Boolean).forEach(src=>{let image=new Image();image.decoding='async';image.src=src;});}
function startEncounter(){
 let m=WORLDS[state.world].mobs[state.level],count=m[5]||1,mechanics=m[8]||{};
 if(encounterIntroTimer)clearTimeout(encounterIntroTimer);
 state.encounterName=m[0];state.encounterType=m[6]||'Normal';state.scene=m[7]||null;
 state.encounterDamageBonus=state.pendingDamageBonus;state.pendingDamageBonus=0;state.encounterDefenseBonus=state.pendingDefenseBonus;state.pendingDefenseBonus=0;
 state.rewardPaid=false;state.lastShardGain=0;state.shopOpen=false;
 state.party.forEach(h=>{h.burn=0;h.passiveReady=true;});
 state.enemies=Array.from({length:count},(_,i)=>({name:m[0],internalName:count>1?`${m[0]} ${String.fromCharCode(65+i)}`:m[0],slot:i,icon:m[1],art:m[4],maxHp:m[2],hp:m[2],damage:m[3],burn:mechanics.burn||0,burnBurst:mechanics.burnBurst||4,pattern:mechanics.pattern||'basic',armor:0,weakened:0,expose:0,poison:0}));
 state.targetIndex=0;state.enemyTurnIndex=0;state.enemyActionCount=0;state.intent=null;state.turn=Math.max(0,state.party.findIndex(h=>h.currentHp>0));state.inspectedHeroId=state.party.find(h=>h.currentHp>0)?.id||null;
 state.log=[count>2?`<b>${count} enemies</b> surround the party.`:count>1?`<b>${count} enemies</b> close in from opposite sides.`:`<b>${m[0].startsWith('The ')?m[0]:`The ${m[0]}`}</b> blocks your path.`];
 let mechanic=mechanicSummary(mechanics.pattern);if(mechanic)state.log.push(mechanic);if(mechanics.burn)state.log.push('<b>Burn:</b> enemy hits add flame. At 3 stacks, it bursts and clears.');if(state.encounterDamageBonus)state.log.push(`<b>Sharpened Sigil:</b> hero attacks deal +${state.encounterDamageBonus} damage.`);if(state.encounterDefenseBonus)state.log.push(`<b>Warding Charm:</b> incoming damage is reduced by ${state.encounterDefenseBonus}.`);
 state.evade=null;state.boost=0;state.boostPower=3;state.cooldowns={};state.exhausted=new Set();state.echoUsed=false;state.animating=true;state.fx=null;state.sceneEntering=true;state.encounterIntro=true;state.cardsArriving=false;
 preloadEncounterAssets(m[4],state.scene?.cutout,state.scene?.bg);
 planEnemyIntent();
 let reducedMotion=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;encounterIntroTimer=setTimeout(()=>finishEncounterIntro(false),reducedMotion?60:encounterIntroDuration());render();
}
function pluralEnemy(name){if(name.endsWith('Wretch'))return name.replace(/Wretch$/,'Wretches');if(name.endsWith('s'))return name;return `${name}s`;}
function encounterIntroDuration(){return state.encounterType==='Boss'?5000:state.encounterType==='Elite'?4200:3600;}
function encounterChoreography(){let count=state.enemies.length;if(count===3)return [{x:18,bottom:4,entry:'-22vw',delay:.04,mirror:1},{x:50,bottom:8,entry:'0vw',delay:.28,mirror:-1},{x:82,bottom:4,entry:'22vw',delay:.12,mirror:-1}];if(count===2)return [{x:34,bottom:0,entry:'-10vw',delay:.06,mirror:1},{x:66,bottom:2,entry:'10vw',delay:.24,mirror:-1}];if(state.encounterType==='Boss')return [{x:50,bottom:-14,entry:'0vw',delay:.28,mirror:1}];if(state.encounterType==='Elite')return [{x:50,bottom:-12,entry:'0vw',delay:.12,mirror:1}];return [{x:50,bottom:0,entry:'0vw',delay:.12,mirror:1}];}
function encounterReveal(){let count=state.enemies.length,choreography=encounterChoreography(),title=count===1?`${state.encounterName} emerges`:`${pluralEnemy(state.encounterName)} emerge`,kind=state.encounterType.toLowerCase(),threat=kind==='boss'?'A sovereign stirs':kind==='elite'?'An elite guardian rises':'Ambush',cutout=state.scene?.cutout;return `<section class="encounter-reveal world-${state.world+1} ${kind} count-${count}" aria-label="${title}"><div class="reveal-vignette"></div><div class="reveal-fog fog-one"></div><div class="reveal-fog fog-two"></div>${kind==='boss'?'<div class="boss-omen"><i></i><i></i><i></i></div>':''}${state.enemies.map((e,i)=>{let c=choreography[i]||{x:50,bottom:0,entry:'0vw',delay:i*.16,mirror:1},style=`--reveal-x:${c.x}%;--reveal-bottom:${c.bottom}vh;--entry-x:${c.entry};--reveal-delay:${c.delay}s;--reveal-mirror:${c.mirror}`,cinematicArt=cutout||e.art;return cinematicArt?`<div class="reveal-creature ${cutout?'is-cutout':''}" style="${style}"><span class="creature-shadow"></span><img src="${cinematicArt}" alt="" /></div>`:`<div class="reveal-symbol" style="${style}">${e.icon}</div>`}).join('')}<div class="reveal-copy"><div class="reveal-threat">${threat} · Fight ${state.level+1} of 5</div><div class="scene-kicker">${state.scene?.name||WORLDS[state.world].name}</div><h2>${title}</h2><p>${state.scene?.intro||'Something moves beyond the edge of sight.'}</p></div><div class="card-forming" aria-hidden="true">The encounter takes shape</div><button class="skip-intro" onclick="skipEncounterIntro()">Skip encounter</button></section>`;}
function commitEncounterCards(){state.encounterIntro=false;state.sceneEntering=false;state.cardsArriving=true;state.animating=false;render();setTimeout(()=>state.cardsArriving=false,1050);}
function finishEncounterIntro(){if(!state.encounterIntro)return;if(encounterIntroTimer){clearTimeout(encounterIntroTimer);encounterIntroTimer=null;}commitEncounterCards();}
function skipEncounterIntro(){finishEncounterIntro(true);}
function ashenAmbience(){let ash=Array.from({length:26},(_,i)=>`<i class="ash-flake" style="--ash-x:${(i*37)%100}%;--ash-size:${1+(i%4)}px;--ash-delay:${-(i*.61)}s;--ash-time:${8+(i%6)*1.3}s;--ash-drift:${-22+(i%7)*8}px"></i>`).join(''),embers=Array.from({length:14},(_,i)=>`<i class="world-ember" style="--ember-x:${6+(i*31)%88}%;--ember-delay:${-(i*.77)}s;--ember-time:${5+(i%5)*1.2}s;--ember-sway:${-28+(i%6)*11}px"></i>`).join(''),special=state.level===0?'<span class="village-fire-glow"></span><span class="ash-smoke smoke-a"></span>':state.level===1?'<span class="village-fire-glow square-glow"></span><span class="ash-smoke smoke-b"></span>':state.level===2?'<span class="basilica-pull"></span>':state.level===3?'<span class="courtyard-heat"></span><span class="swing-chain chain-left"></span><span class="swing-chain chain-right"></span>':'<span class="last-flame-pulse"></span>';return `<div class="scene-ambience ashen-life ashen-${state.level}" aria-hidden="true">${special}${ash}${embers}</div>`;}
function sceneAmbience(){if(!state.scene)return '';if(state.world===1)return ashenAmbience();if(state.world!==0)return '';if(state.level===0){let leaves=Array.from({length:16},(_,i)=>`<i class="wind-leaf" style="--leaf-y:${14+(i*19)%68}%;--leaf-size:${5+(i%4)*2}px;--leaf-delay:${-(i*.83)}s;--leaf-time:${8+(i%5)*1.35}s;--leaf-drift:${-8+(i%5)*4}vh"></i>`).join('');return `<div class="scene-ambience threshold-wind" aria-hidden="true"><span class="cold-gust gust-a"></span><span class="cold-gust gust-b"></span>${leaves}</div>`;}if(state.level===1)return `<div class="scene-ambience hunter-stalk" aria-hidden="true"><span class="ground-fog fog-back"></span><span class="wolf-shadow wolf-left"><img src="assets/enemies/cinematic/briar-hound-cutout.webp" alt="" /></span><span class="wolf-shadow wolf-right"><img src="assets/enemies/cinematic/briar-hound-cutout.webp" alt="" /></span><span class="forest-edge edge-left"></span><span class="forest-edge edge-right"></span><span class="ground-fog fog-middle"></span><span class="ground-fog fog-front"></span></div>`;if(state.level===2){let spores=Array.from({length:18},(_,i)=>`<i class="spore-mote" style="--mote-x:${7+(i*29)%88}%;--mote-size:${2+(i%4)*1.4}px;--mote-delay:${-(i*.71)}s;--mote-time:${8+(i%6)*1.4}s;--mote-sway:${-35+(i%7)*12}px"></i>`).join('');return `<div class="scene-ambience fungal-spores" aria-hidden="true"><span class="hollow-glow"></span>${spores}</div>`;}if(state.level===3){let debris=Array.from({length:14},(_,i)=>`<i class="grove-debris" style="--debris-x:${5+(i*23)%92}%;--debris-size:${2+(i%4)*1.5}px;--debris-delay:${-(i*.92)}s;--debris-time:${7+(i%5)*1.6}s"></i>`).join('');return `<div class="scene-ambience broken-grove" aria-hidden="true"><span class="shrine-dust"></span>${debris}</div>`;}let wisps=Array.from({length:16},(_,i)=>`<i class="root-wisp" style="--wisp-x:${12+(i*31)%78}%;--wisp-size:${2+(i%3)*1.5}px;--wisp-delay:${-(i*.8)}s;--wisp-time:${7+(i%5)*1.2}s;--wisp-sway:${-26+(i%6)*11}px"></i>`).join('');return `<div class="scene-ambience heartroot-energy" aria-hidden="true"><span class="throne-pulse"></span>${wisps}</div>`;}
function echoSupportCards(){let echoes=equippedEchoes();if(!echoes.length)return '';let disabled=state.animating||state.echoUsed||!currentTarget();return `<aside class="echo-hand ${state.echoUsed?'spent':''}" aria-label="Echo support hand"><div class="echo-hand-heading"><span>Echo support</span><b>${state.echoUsed?'Spent this fight':'Choose one · free action'}</b></div>${echoes.map(e=>`<button class="echo-support ${state.echoUsed?'spent':''}" onclick="summonEcho('${e.id}')" ${disabled?'disabled':''} aria-label="Cast ${e.name}'s Echo: ${e.ability.name}. ${abilityText(e.ability)}"><span class="echo-type ${echoKind(e.ability).toLowerCase()}">${echoKind(e.ability)}</span><b>${e.icon} ${e.name} · ${e.ability.name}</b><small>${state.echoUsed?'Unavailable until next fight':`R${e.ability.rank||1} · ${abilityText(e.ability)}`}</small></button>`).join('')}</aside>`;}
function game(){let w=WORLDS[state.world];let active=state.party[state.turn%state.party.length];if(active?.currentHp<=0)active=nextLiving();let inspected=state.party.find(h=>h.id===state.inspectedHeroId)||active,isActing=inspected?.id===active?.id;app.innerHTML=`<div class="combat-screen world-${state.world+1} ${state.encounterType.toLowerCase()} ${state.sceneEntering?'scene-entering':''} ${state.encounterIntro?'encounter-cinematic':''} ${state.cardsArriving?'cards-arriving':''} ${state.fx?.kind==='enemy'?'enemy-retaliating':''}" ${state.scene?`style="--scene:url('${state.scene.bg}')"`:''}><div class="combat-shade"></div>${sceneAmbience()}${state.encounterIntro?encounterReveal():''}<header class="combat-hud"><div class="combat-topbar">${topbar()}</div><section class="world-strip"><div class="world-title"><div class="world-number">0${state.world+1}</div><div><div class="eyebrow" style="color:${w.color}">${w.tone}</div><h3>${w.name}</h3></div></div><div class="path">${[0,1,2,3,4].map((n,i)=>`${i?'<span class="dash"></span>':''}<span class="node ${i<state.level?'done':i===state.level?'active':''} ${i===3?'elite-node':''}">${i===4?'♛':i===3?'◆':i+1}</span>`).join('')}</div></section></header><main class="battlefield">${echoSupportCards()}${state.scene?`<section class="scene-story"><div class="scene-kicker">${state.scene.name}</div><p>${state.scene.intro}</p></section>`:''}<section class="enemy-stage count-${state.enemies.length}"><div class="encounter-label ${state.encounterType.toLowerCase()}">${state.encounterType} · Fight ${state.level+1} of 5</div><div class="enemy-zone">${state.enemies.map(enemyCard).join('')}</div></section><section class="command-deck"><div class="action-tray"><div class="action-heading"><div><span>${isActing?'Ready to act':'Viewing loadout'}</span><strong>${inspected?.name||''}</strong></div>${!isActing&&active?`<button class="return-turn" onclick="inspectHero('${active.id}')">Return to ${active.name}</button>`:`<small>Choose an ability, then strike your target</small>`}</div><div class="abilities">${inspected?inspected.abilities.map((a,i)=>{let cd=abilityCooldown(inspected.id,a.name);return `<button class="ability-btn ${cd?'cooling-down':''} ${state.fx?.abilityName===a.name?'ability-cast':''}" title="${abilityText(a)}${cd?` ${cd} turn remaining.`:''}" ${state.animating||!isActing||state.exhausted.has(a.name)||cd||inspected.currentHp<=0?'disabled':''} onclick="useAbility('${inspected.id}',${i})"><span class="ability-icon">${a.icon||'✦'}</span><span class="ability-name">${a.name}</span><span class="ability-rank ${cd?'cooldown':''}">${cd?`CD ${cd}`:`R${a.rank||1}`}</span><span class="ability-tooltip">${abilityText(a)}${cd?` <b>${cd} turn remaining.</b>`:''}</span></button>`;}).join(''):''}</div></div><div class="hero-deck">${state.party.map(h=>memberCard(h,active,inspected)).join('')}</div><div class="combat-log"><span>Battle log</span>${state.log.slice(-3).join('<br>')}</div></section></main></div>`;}
function inspectHero(id){if(state.party.some(h=>h.id===id)){state.inspectedHeroId=id;render();}}
function jumpEncounter(delta){if(state.screen!=='game'||state.encounterIntro||state.animating)return;let next=Math.max(0,Math.min(4,state.level+delta));if(next===state.level)return;document.querySelector('#modal')?.remove();state.level=next;state.party.forEach(h=>h.currentHp=h.maxHp);startEncounter();}
function jumpWorld(delta){if(state.screen!=='game'||state.encounterIntro||state.animating)return;let next=Math.max(0,Math.min(WORLDS.length-1,state.world+delta));if(next===state.world)return;document.querySelector('#modal')?.remove();state.world=next;state.level=0;state.party.forEach(h=>{h.currentHp=h.maxHp;h.burn=0;});state.log=[];startEncounter();}
function heroAbilitySlots(h,active,dead){return Array.from({length:4},(_,i)=>{let a=h.abilities[i];if(!a)return `<span class="hero-ability-empty"><span>◇</span><small>Empty</small></span>`;let cd=abilityCooldown(h.id,a.name),canUse=active?.id===h.id&&!state.animating&&!dead&&!state.exhausted.has(a.name)&&!cd,click=canUse?`useAbility('${h.id}',${i})`:(!state.animating&&!dead?`inspectHero('${h.id}')`:``),disabled=active?.id===h.id&&(cd||state.exhausted.has(a.name));return `<button type="button" class="hero-ability-btn ${canUse?'can-use':'locked'} ${cd?'cooling-down':''} ${state.fx?.abilityName===a.name&&state.fx?.heroId===h.id?'ability-cast':''}" ${disabled?'disabled':''} title="${abilityText(a)}${cd?` ${cd} turn remaining.`:''}" aria-label="${a.name}, rank ${a.rank||1}. ${abilityText(a)}${cd?` ${cd} turn remaining.`:''}" onclick="event.stopPropagation();${click}"><span class="hero-ability-icon">${a.icon||'✦'}</span><span class="hero-ability-name">${a.name}</span><span class="hero-ability-rank ${cd?'cooldown':''}">${cd?`CD ${cd}`:`R${a.rank||1}`}</span><span class="ability-tooltip">${abilityText(a)}${cd?` <b>${cd} turn remaining.</b>`:''}</span></button>`}).join('');}
function mechanicSummary(pattern){return {regrow:'<b>Regrowth:</b> every third enemy action heals a wounded Wretch.',pack:'<b>Pack Hunt:</b> 7 damage with three Hounds, 6 with two, and 5 alone.',spores:'<b>Spore Burst:</b> every third enemy action damages the entire party.',slam:'<b>Pillar Slam:</b> every third enemy action is a crushing heavy blow.',drain:'<b>Heartroot Drain:</b> every third enemy action steals health.',kindle:'<b>Kindled Claws:</b> Imp attacks build Burn.',guard:'<b>Ash Guard:</b> every third enemy action raises protective armor.',rite:'<b>Censer Rite:</b> every third enemy action spreads Burn to the party.',pounce:'<b>Pounce:</b> every third enemy action is a heavy leap with extra Burn.',lastflame:'<b>Last Flame:</b> every third enemy action scorches the entire party.'}[pattern]||'';}
function planEnemyIntent(){state.intent=null;let livingIndices=state.enemies.map((e,i)=>e.hp>0?i:-1).filter(i=>i>=0),livingHeroes=state.party.filter(h=>h.currentHp>0);if(!livingIndices.length||!livingHeroes.length)return;let attackerIndex=livingIndices[state.enemyTurnIndex%livingIndices.length],attacker=state.enemies[attackerIndex],target=livingHeroes[Math.floor(Math.random()*livingHeroes.length)],actionNumber=state.enemyActionCount+1,everyThird=actionNumber%3===0,kind='attack',name=attacker.pattern==='kindle'?'Kindled Claw':'Strike',icon='⚔️',damage=attacker.damage,burn=attacker.burn||0,healAmount=0,armorAmount=0,all=false;if(attacker.pattern==='regrow'&&everyThird&&state.enemies.some(e=>e.hp>0&&e.hp<e.maxHp)){kind='regrow';name='Regrow';icon='🌿';damage=0;burn=0;healAmount=4;target=null;}else if(attacker.pattern==='pack'){name='Pack Hunt';icon='🐺';damage+=Math.max(0,livingIndices.length-1);}else if(attacker.pattern==='spores'&&everyThird){kind='spores';name='Spore Burst';icon='🍄';damage=2;burn=0;all=true;target=null;}else if(attacker.pattern==='slam'&&everyThird){kind='slam';name='Pillar Slam';icon='🪨';damage+=5;}else if(attacker.pattern==='drain'&&everyThird){kind='drain';name='Heartroot Drain';icon='🌱';damage=Math.max(1,damage-2);healAmount=6;}else if(attacker.pattern==='guard'&&everyThird){kind='guard';name='Ash Guard';icon='🛡️';damage=0;burn=0;armorAmount=6;target=null;}else if(attacker.pattern==='rite'&&everyThird){kind='rite';name='Censer Rite';icon='🔥';damage=0;burn=1;all=true;target=null;}else if(attacker.pattern==='pounce'&&everyThird){kind='pounce';name='Pounce';icon='🐅';damage+=5;burn=Math.max(2,burn);}else if(attacker.pattern==='lastflame'&&everyThird){kind='lastflame';name='Last Flame';icon='☀️';damage=7;burn=1;all=true;target=null;}state.intent={attackerIndex,kind,name,icon,damage,burn,healAmount,armorAmount,all,targetId:target?.id||null};}
function enemyIntentMarkup(e,i,dead){
 if(dead)return '<div class="intent defeated-intent"><b>Defeated</b><span>No longer acts</span></div>';
 let intent=state.intent?.attackerIndex===i?state.intent:null;
 if(!intent)return '<div class="intent waiting-intent"><b>Waiting</b></div>';
 let damage=intent.damage?Math.max(1,intent.damage-(e.weakened||0)):0,target=state.party.find(h=>h.id===intent.targetId),details=intent.kind==='guard'?`+${intent.armorAmount} armor`:intent.kind==='regrow'?`Heal ${intent.healAmount}`:[damage?`${damage} damage`:'',intent.burn?`+${intent.burn} Burn`:''].filter(Boolean).join(' · '),targetText=intent.all?'All heroes':target?`→ ${target.name}`:'';
 let burnTargets=intent.burn?(intent.all?state.party.filter(h=>h.currentHp>0):target?[target]:[]).filter(h=>state.evade!==h.id&&(h.burn||0)+intent.burn>=3):[],burnWarning=burnTargets.length?`🔥 Eruption +${e.burnBurst||4}: ${burnTargets.map(h=>h.name).join(', ')}`:'';
 return `<div class="intent active-intent" title="Next enemy action"><b>${intent.icon} ${intent.name}</b>${details?`<span>${details}</span>`:''}${targetText?`<small>${targetText}</small>`:''}${burnWarning?`<em class="intent-warning">${burnWarning}</em>`:''}</div>`;
}
function enemyStatusMarkup(e){if(e.hp<=0)return '';let effects=[];if(e.armor)effects.push(`<span class="enemy-status armor" title="Armor absorbs incoming damage">🛡 ${e.armor}</span>`);if(e.poison)effects.push(`<span class="enemy-status poison" title="Takes ${e.poison} poison damage after every enemy turn">☠ ${e.poison}</span>`);if(e.weakened)effects.push(`<span class="enemy-status weakened" title="Next attack deals ${e.weakened} less damage">↓ ${e.weakened}</span>`);if(e.expose)effects.push(`<span class="enemy-status exposed" title="Next hero attack gains ${e.expose} damage">◎ +${e.expose}</span>`);return effects.length?`<div class="enemy-statuses" aria-label="Active effects">${effects.join('')}</div>`:'';}
function memberCard(h,active,inspected){let pct=Math.max(0,h.currentHp/h.maxHp*100),shownHp=Math.max(0,h.currentHp),burn=h.burn||0,evading=state.evade===h.id,dead=h.currentHp<=0,locked=dead||state.animating,healFx=(state.fx?.heals||[]).filter(x=>x.heroId===h.id).reduce((sum,x)=>sum+x.amount,0),multiDamage=(state.fx?.heroDamages||[]).filter(x=>x.heroId===h.id).reduce((sum,x)=>sum+x.amount,0),singleDamage=state.fx?.heroDamage?.heroId===h.id?state.fx.heroDamage.amount:0,damageFx=multiDamage+singleDamage,evaded=state.fx?.evadedHeroId===h.id,passiveSpent=h.passiveOnce&&h.passiveReady===false;return `<article class="battle-hero-card ${active?.id===h.id?'active-turn':''} ${inspected?.id===h.id?'inspected':''} ${dead?'fallen':''} ${locked?'hero-locked':''} ${state.fx?.heroId===h.id?'hero-strike':''} ${damageFx?'hero-hit':''} ${healFx?'hero-healed':''}" ${locked?'':`onclick="inspectHero('${h.id}')"`} aria-label="${h.name}, ${shownHp} of ${h.maxHp} health${burn?`, ${burn} of 3 Burn`:''}${evading?', Evade ready':''}. ${h.passive}${passiveSpent?' spent':' active'}">${damageFx?`<span class="combat-number damage-number">-${damageFx}</span>`:''}${healFx?`<span class="combat-number heal-number">+${healFx}</span>`:''}${evaded?`<span class="combat-number evade-number">Evade</span>`:''}<div class="battle-hero-art">${h.art?`<img src="${h.art}" alt="${h.name}" />`:h.icon}</div><div class="battle-hero-copy"><div class="class">${active?.id===h.id?'Current turn':h.role}</div><h3>${h.name}</h3><div class="hp-row"><div class="bar"><span style="width:${pct}%"></span></div><b>${shownHp}</b><small>/${h.maxHp}</small></div><span class="passive-status ${passiveSpent?'spent':''}" title="${h.passiveDesc}">${h.passive}${passiveSpent?' · spent':''}</span>${burn?`<span class="burn-status" title="At 3 stacks, Burn bursts and clears">🔥 ${burn}/3</span>`:''}${evading?`<span class="evade-status" title="The next enemy attack against this hero is evaded">🌘 Evade ready</span>`:''}</div><div class="hero-abilities" aria-label="${h.name}'s abilities">${heroAbilitySlots(h,active,dead)}</div></article>`;}
function enemyCard(e,i){let pct=Math.max(0,e.hp/e.maxHp*100),dead=e.hp<=0,damageFx=(state.fx?.enemyDamage||[]).filter(x=>x.index===i).reduce((sum,x)=>sum+x.amount,0),healFx=state.fx?.enemyHeal?.index===i?state.fx.enemyHeal.amount:0,hit=state.fx?.hitTargets?.includes(i),defeated=state.fx?.defeated?.includes(i),acting=state.intent?.attackerIndex===i&&!dead;return `<button class="enemy-card enemy-select ${state.targetIndex===i&&!dead?'targeted':''} ${acting?'intending':''} ${dead?'defeated':''} ${hit?'enemy-hit':''} ${state.fx?.enemyAttackerIndex===i?'enemy-strike':''} ${defeated?'just-defeated':''}" style="--enemy-index:${i}" onclick="selectTarget(${i})" ${dead||state.animating?'disabled':''}>${damageFx?`<span class="combat-number damage-number">-${damageFx}</span>`:''}${healFx?`<span class="combat-number heal-number">+${healFx}</span>`:''}${e.art?`<div class="enemy-portrait"><img class="${i%2?'mirrored':''}" src="${e.art}" alt="${e.name}" /></div>`:`<div class="enemy-art">${e.icon}</div>`}<div class="enemy-data"><div class="class">${dead?'Defeated':state.targetIndex===i?'Current target':state.encounterType}</div><h2>${e.name}</h2>${enemyStatusMarkup(e)}<div class="hp-row"><div class="bar enemy"><span style="width:${pct}%"></span></div><b>${Math.max(0,e.hp)}</b><small>/${e.maxHp}</small></div>${enemyIntentMarkup(e,i,dead)}</div></button>`;}
function selectTarget(i){if(state.enemies[i]?.hp>0){state.targetIndex=i;render();}}
function currentTarget(){let target=state.enemies[state.targetIndex];if(!target||target.hp<=0){state.targetIndex=state.enemies.findIndex(e=>e.hp>0);target=state.enemies[state.targetIndex];}return target;}
function nextLiving(){return state.party.find(h=>h.currentHp>0);}
function lowest(){return [...state.party].filter(h=>h.currentHp>0).sort((a,b)=>a.currentHp/a.maxHp-b.currentHp/b.maxHp)[0];}
function heal(h,n){if(!h)return;let before=h.currentHp;h.currentHp=Math.min(h.maxHp,h.currentHp+n);let restored=Math.max(0,h.currentHp-before);if(restored&&state.fx?.kind==='hero')state.fx.heals.push({heroId:h.id,amount:restored});}
function recordHeroDamage(heroId,amount){if(!state.fx||amount<=0)return;state.fx.heroDamages=state.fx.heroDamages||[];let existing=state.fx.heroDamages.find(x=>x.heroId===heroId);if(existing)existing.amount+=amount;else state.fx.heroDamages.push({heroId,amount});}
function applyHeroDamage(hero,amount,source='enemy'){if(!hero||hero.currentHp<=0||amount<=0)return 0;let ward=source!=='pact'?(state.encounterDefenseBonus||0):0,damage=Math.max(0,amount-ward),steadfast=damage>0&&source!=='pact'&&hero.passive==='Steadfast'&&hero.passiveReady;if(ward)state.log.push(`<b>Warding Charm</b> reduces damage to ${hero.name} by ${Math.min(ward,amount)}.`);if(steadfast){damage=Math.max(0,damage-3);hero.passiveReady=false;state.log.push(`<b>${hero.name}'s Steadfast</b> reduces the hit by 3.`);}let before=hero.currentHp,sol=state.party.find(h=>h.passive==='Last Light'&&h.currentHp>0&&h.passiveReady);hero.currentHp-=damage;if(hero.currentHp<=0&&sol){hero.currentHp=1;sol.passiveReady=false;state.log.push(`<b>${sol.name}'s Last Light</b> keeps ${hero.name} standing at 1 health.`);}let dealt=Math.max(0,before-hero.currentHp);recordHeroDamage(hero.id,dealt);return dealt;}
function applyBurn(hero,stacks,burst=4){if(!hero||hero.currentHp<=0||!stacks)return 0;hero.burn=(hero.burn||0)+stacks;state.log.push(`<b>${hero.name}</b> gains ${stacks} Burn (${hero.burn}/3).`);if(hero.burn<3)return 0;hero.burn=0;let dealt=applyHeroDamage(hero,burst,'burn');state.log.push(`Burn erupts for <b>${burst}</b> damage and clears.`);return dealt;}
function hit(n,user){let target=currentTarget();if(!target)return 0;let index=state.enemies.indexOf(target),before=target.hp,expose=target.expose||0,boost=state.boost>0?state.boostPower:0,sigil=state.encounterDamageBonus||0,opportunist=user.passive==='Opportunist'&&target.hp<target.maxHp/2?2:0,keenEye=user.passive==='Keen Eye'&&user.passiveReady?4:0,total=n+expose+boost+sigil+opportunist+keenEye,blocked=Math.min(target.armor||0,total);if(keenEye){user.passiveReady=false;state.log.push(`<b>${user.name}'s Keen Eye</b> adds 4 damage.`);}if(opportunist)state.log.push(`<b>${user.name}'s Opportunist</b> adds 2 damage.`);if(sigil)state.log.push(`<b>Sharpened Sigil</b> adds ${sigil} damage.`);if(expose){state.log.push(`The exposed weakness adds <b>${expose}</b> damage.`);target.expose=0;}if(boost>0)state.boost--;if(blocked){target.armor-=blocked;total-=blocked;state.log.push(`${target.name}'s armor blocks <b>${blocked}</b> damage.`);}target.hp-=total;if(state.fx){if(total)state.fx.enemyDamage.push({index,amount:total});if(!state.fx.hitTargets.includes(index))state.fx.hitTargets.push(index);if(before>0&&target.hp<=0&&!state.fx.defeated.includes(index))state.fx.defeated.push(index);}state.log.push(`<b>${user.name}</b> deals ${total} damage to ${target.name}.`);return total;}
function useAbility(id,index){let user=state.party.find(h=>h.id===id),active=state.party[state.turn%state.party.length],a=user?.abilities[index],target=currentTarget();if(state.animating||!user||!a||user.currentHp<=0||active?.id!==user.id||!target||abilityCooldown(id,a.name))return;tickHeroCooldowns(id);if(a.cooldown)setAbilityCooldown(id,a.name,a.cooldown);state.animating=true;state.fx={kind:'hero',heroId:id,abilityName:a.name,enemyDamage:[],hitTargets:[],defeated:[],heals:[],heroDamages:[],heroDamage:null};
 if(a.type==='damage') hit(a.value+(a.execute&&target.hp<target.maxHp/2?a.execute:0),user);
 if(a.type==='hybrid'){hit(a.value,user);heal(lowest(),a.heal);state.log.push(`Restorative light heals an ally for <b>${a.heal}</b>.`)}
 if(a.type==='weaken'){hit(a.value,user);if(target.hp>0){let weaken=(a.weaken||4)+(user.passive==='Lingering Curse'?2:0);target.weakened=Math.max(target.weakened,weaken);if(user.passive==='Lingering Curse')state.log.push(`<b>${user.name}'s Lingering Curse</b> deepens Weaken by 2.`);}}
 if(a.type==='double'){hit(a.value,user);if(Math.random()<.45){hit(a.value,user);state.log.push('The second shot finds its mark!')}}
 if(a.type==='poison'){hit(a.value,user);if(target.hp>0){let poison=(a.dot||3)+(user.passive==='Lingering Curse'?1:0);target.poison+=poison;if(user.passive==='Lingering Curse')state.log.push(`<b>${user.name}'s Lingering Curse</b> adds 1 Poison.`);}}
 if(a.type==='evade'){hit(a.value,user);state.evade=user.id;if(a.cooldown)state.log.push(`<b>${a.name}</b> enters cooldown for one ${user.name} turn.`);}
 if(a.type==='pact'){applyHeroDamage(user,3,'pact');hit(a.value,user);}
 if(a.type==='heal'){state.party.forEach(h=>heal(h,a.value));state.log.push(`<b>${user.name}</b> mends the party for ${a.value}.`)}
 if(a.type==='selfheal'){hit(a.value,user);heal(user,a.heal);}
 if(a.type==='expose'){hit(a.value,user);if(target.hp>0)target.expose=a.bonus||6;}
 if(a.type==='meteor'){hit(a.value,user);state.exhausted.add(a.name);}
 if(a.type==='cry'){hit(a.value,user);state.boost=2;state.boostPower=a.power||3;}
 if(state.party.every(h=>h.currentHp<=0)){render();setTimeout(partyFell,600);return;}if(state.enemies.every(e=>e.hp<=0)){render();setTimeout(victory,650);return;}currentTarget();if(!state.enemies[state.intent?.attackerIndex]||state.enemies[state.intent.attackerIndex].hp<=0||(state.intent?.targetId&&!state.party.some(h=>h.id===state.intent.targetId&&h.currentHp>0)))planEnemyIntent();render();setTimeout(enemyTurn,380);}
function enemyTurn(){state.fx={kind:'enemy',enemyDamage:[],hitTargets:[],defeated:[],heals:[],heroDamages:[],heroDamage:null,enemyAttackerIndex:null,enemyHeal:null,evadedHeroId:null};state.enemies.filter(e=>e.hp>0&&e.poison).forEach(e=>{let index=state.enemies.indexOf(e),before=e.hp;e.hp-=e.poison;state.fx.enemyDamage.push({index,amount:e.poison});state.fx.hitTargets.push(index);if(before>0&&e.hp<=0)state.fx.defeated.push(index);state.log.push(`Poison deals <b>${e.poison}</b> damage to ${e.name}.`);});if(state.enemies.every(e=>e.hp<=0)){render();setTimeout(victory,600);return;}let intended=state.enemies[state.intent?.attackerIndex],target=state.party.find(h=>h.id===state.intent?.targetId);if(!intended||intended.hp<=0||(state.intent?.targetId&&(!target||target.currentHp<=0)))planEnemyIntent();let intent=state.intent,attacker=state.enemies[intent?.attackerIndex];if(!intent||!attacker){if(state.party.every(h=>h.currentHp<=0)){render();setTimeout(partyFell,600);}else{state.animating=false;state.fx=null;render();}return;}state.fx.enemyAttackerIndex=intent.attackerIndex;let damage=Math.max(intent.damage?1:0,intent.damage-(attacker.weakened||0)),damaging=!['regrow','guard','rite'].includes(intent.kind);
 if(intent.kind==='regrow'){let wounded=state.enemies.filter(e=>e.hp>0&&e.hp<e.maxHp).sort((a,b)=>(b.maxHp-b.hp)-(a.maxHp-a.hp))[0];if(wounded){let before=wounded.hp;wounded.hp=Math.min(wounded.maxHp,wounded.hp+intent.healAmount);let restored=wounded.hp-before;state.fx.enemyHeal={index:state.enemies.indexOf(wounded),amount:restored};state.log.push(`<b>${attacker.name}</b> uses Regrow and restores ${restored} health.`);}else state.log.push(`<b>${attacker.name}</b> finds no wound for Regrow.`);}
 else if(intent.kind==='guard'){attacker.armor=Math.min(12,(attacker.armor||0)+intent.armorAmount);state.log.push(`<b>${attacker.name}</b> raises Ash Guard and gains ${intent.armorAmount} armor.`);}
 else if(intent.kind==='rite'){state.log.push(`<b>${attacker.name}</b> performs Censer Rite.`);state.party.filter(h=>h.currentHp>0).forEach(h=>applyBurn(h,intent.burn,attacker.burnBurst));}
 else if(intent.all){state.log.push(`<b>${attacker.name}</b> unleashes ${intent.name} on the entire party.`);state.party.filter(h=>h.currentHp>0).forEach(h=>{if(state.evade===h.id){state.log.push(`<b>${h.name}</b> slips through ${intent.name}.`);state.fx.evadedHeroId=h.id;state.evade=null;return;}applyHeroDamage(h,damage,intent.name);if(h.currentHp>0&&intent.burn)applyBurn(h,intent.burn,attacker.burnBurst);});}
 else {let victim=state.party.find(h=>h.id===intent.targetId);if(state.evade===victim?.id){state.log.push(`<b>${victim.name}</b> slips through ${attacker.name}'s ${intent.name}.`);state.fx.evadedHeroId=victim.id;state.evade=null;}else if(victim){let dealt=applyHeroDamage(victim,damage,intent.name);state.log.push(`${attacker.name} uses <b>${intent.name}</b> on ${victim.name} for ${dealt}.`);if(victim.currentHp>0&&intent.burn)applyBurn(victim,intent.burn,attacker.burnBurst);if(intent.kind==='drain'&&dealt){let before=attacker.hp;attacker.hp=Math.min(attacker.maxHp,attacker.hp+intent.healAmount);let restored=attacker.hp-before;if(restored){state.fx.enemyHeal={index:intent.attackerIndex,amount:restored};state.log.push(`${attacker.name} drains <b>${restored}</b> health.`);}}}}
 if(damaging)attacker.weakened=0;state.enemyActionCount++;state.enemyTurnIndex++;if(state.party.every(h=>h.currentHp<=0)){render();setTimeout(partyFell,600);return;}do{state.turn++}while(state.party[state.turn%state.party.length].currentHp<=0);state.inspectedHeroId=state.party[state.turn%state.party.length].id;planEnemyIntent();render();setTimeout(()=>{state.animating=false;state.fx=null;render();},520);}
function rollRewards(){let rewards=[],used=new Set();for(let slot=0;slot<2;slot++){let fresh=REWARD_ABILITIES.filter(a=>!state.learnedAbilities.has(a.name)&&!used.has(a.name));let upgrades=state.party.flatMap(h=>h.abilities.map((a,index)=>({hero:h,ability:a,index}))).filter(x=>(x.ability.rank||1)<MAX_ABILITY_RANK&&!used.has(x.ability.name));let allowDuplicate=!rewards.some(r=>r.upgrade),takeDuplicate=upgrades.length&&(!fresh.length||(allowDuplicate&&Math.random()<DUPLICATE_CHANCE));if(takeDuplicate){let pick=upgrades[Math.floor(Math.random()*upgrades.length)],preview=rankPreview(pick.ability);rewards.push({...preview,upgrade:true,sourceName:pick.ability.name,targetHeroId:pick.hero.id,targetAbilityIndex:pick.index});used.add(pick.ability.name);}else if(fresh.length){let pick=fresh[Math.floor(Math.random()*fresh.length)];rewards.push({...pick,rank:1,desc:abilityText({...pick,rank:1})});used.add(pick.name);}else if(upgrades.length){let pick=upgrades[Math.floor(Math.random()*upgrades.length)],preview=rankPreview(pick.ability);rewards.push({...preview,upgrade:true,sourceName:pick.ability.name,targetHeroId:pick.hero.id,targetAbilityIndex:pick.index});used.add(pick.ability.name);}}return rewards;}
function victoryShardReward(){return state.encounterType==='Boss'?25:state.encounterType==='Elite'?20:10;}
function victory(){if(state.screen!=='game'||state.enemies.some(e=>e.hp>0))return;state.animating=false;state.fx=null;if(!state.rewardPaid){state.lastShardGain=victoryShardReward();state.shards+=state.lastShardGain;state.rewardPaid=true;}if(state.level===4&&state.world===4){endGame();return;}state.rewards=rollRewards();state.assigned=0;state.pendingReplacement=null;showRewards();}
function rewardActions(a,i){if(a.given)return `<div class="assigned">✓ ${a.given}</div>`;if(a.upgrade){let h=state.party.find(x=>x.id===a.targetHeroId);return `<div class="rank-action"><button onclick="claimUpgrade(${i})">${h.icon} Rank up ${h.name}'s ${a.name}</button><small>No ability slot required</small></div>`;}let pending=state.pendingReplacement;if(pending?.rewardIndex===i){let h=state.party.find(x=>x.id===pending.heroId);return `<div class="replacement"><div class="replacement-title">${h.name} is full · replace one ability</div>${h.abilities.map((old,slot)=>{let locked=state.rewards.some(r=>r.upgrade&&!r.given&&r.targetHeroId===h.id&&r.sourceName===old.name);return `<button ${locked?'disabled':''} onclick="replaceAbility(${i},'${h.id}',${slot})"><span>${old.icon}</span><b>${old.name} · R${old.rank||1}</b><small>${locked?'Claim its pending rank first':`Replace with ${a.name}`}</small></button>`;}).join('')}<button class="cancel-swap" onclick="cancelReplacement()">Cancel replacement</button></div>`;}return `<div class="assign">${state.party.map(h=>`<button onclick="assignReward(${i},'${h.id}')">${h.icon} ${h.name}${h.currentHp<=0?' · Fallen':h.abilities.length>=4?' · Swap':' · '+h.abilities.length+'/4'}</button>`).join('')}</div>`;}
function showRewards(){let done=state.assigned===state.rewards.length,label=done?'Continue onward':state.assigned?'Continue without the other reward':'Continue without rewards';document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><section class="panel modal"><div class="eyebrow">Victory reward · +${state.lastShardGain} shards</div><h2>Two abilities survived</h2>${state.scene?.outro?`<div class="story-beat"><span>${state.scene.name}</span><p>${state.scene.outro}</p></div>`:''}<p>New abilities are most common. Uncommon duplicates rank up the equipped copy without using another slot. Every reward is optional.</p><div class="rewards">${state.rewards.map((a,i)=>`<div class="reward-card ${a.upgrade?'rank-reward':''} ${state.pendingReplacement?.rewardIndex===i?'swapping':''}"><div class="icon">${a.icon}</div><div class="reward-rank">${a.upgrade?`Rank up · R${a.rank}`:'New ability · R1'}</div><h3>${a.name}</h3><p>${abilityText(a)}</p>${rewardActions(a,i)}</div>`).join('')}</div><div class="reward-footer"><button class="primary" onclick="continueRun()">${label}</button>${done?'':`<small>Unclaimed rewards will be left behind.</small>`}</div></section></div>`)}
function claimUpgrade(i){let reward=state.rewards[i],h=state.party.find(x=>x.id===reward?.targetHeroId),a=h?.abilities.find(x=>x.name===reward?.sourceName);if(!reward||!reward.upgrade||reward.given||!a)return;rankUpAbility(a);reward.given=`${h.name}'s ${a.name} reached Rank ${a.rank}`;state.assigned++;document.querySelector('#modal').remove();showRewards();}
function assignReward(i,id){let a=state.rewards[i],h=state.party.find(x=>x.id===id);if(!a||a.upgrade||a.given||!h)return;if(h.abilities.length>=4){state.pendingReplacement={rewardIndex:i,heroId:id};document.querySelector('#modal').remove();showRewards();return;}h.abilities.push({...a,rank:1,desc:abilityText(a)});state.learnedAbilities.add(a.name);a.given=`Given to ${h.name}`;state.assigned++;state.pendingReplacement=null;document.querySelector('#modal').remove();showRewards();}
function replaceAbility(i,id,slot){let a=state.rewards[i],h=state.party.find(x=>x.id===id),old=h?.abilities[slot],locked=state.rewards.some(r=>r.upgrade&&!r.given&&r.targetHeroId===id&&r.sourceName===old?.name);if(!a||a.upgrade||a.given||!h||!old||locked)return;h.abilities.splice(slot,1,{...a,rank:1,desc:abilityText(a)});state.learnedAbilities.add(a.name);a.given=`Given to ${h.name} · replaced ${old.name}`;state.assigned++;state.pendingReplacement=null;document.querySelector('#modal').remove();showRewards();}
function cancelReplacement(){state.pendingReplacement=null;document.querySelector('#modal').remove();showRewards();}
function shopItemMarkup(item){
 let bought=state.shopBought.has(item.id),affordable=state.shards>=item.price,tierClass=item.id==='revive'?'major':'small';
 if(item.id==='revive'){
  let fallen=state.party.filter(h=>h.currentHp<=0),actions=bought?'<div class="shop-purchased">✓ Phoenix Thread used</div>':fallen.length?`<div class="shop-revive-actions">${fallen.map(h=>`<button ${affordable?'':'disabled'} onclick="buyShopItem('revive','${h.id}')">Revive ${h.name} · ${item.price} ✦</button>`).join('')}</div>`:'<div class="shop-safe">Your full party survived</div>';
  return `<article class="shop-card ${tierClass} ${bought?'purchased':''} ${!fallen.length?'unavailable':''}"><div class="shop-card-top"><span class="shop-icon">${item.icon}</span><span class="shop-tier">${item.tier}</span></div><div class="shop-price">${item.price} ✦</div><h3>${item.name}</h3><strong class="shop-effect">${item.effect}</strong><p>${item.desc}</p>${actions}</article>`;
 }
 let useful=item.id!=='heal'||state.party.some(h=>h.currentHp>0&&h.currentHp<h.maxHp),disabled=bought||!affordable||!useful,label=bought?'Purchased':!useful?'Already at full health':!affordable?`Need ${item.price-state.shards} more shards`:`Buy · ${item.price} ✦`;
 return `<article class="shop-card ${tierClass} ${bought?'purchased':''} ${!useful?'unavailable':''}"><div class="shop-card-top"><span class="shop-icon">${item.icon}</span><span class="shop-tier">${item.tier}</span></div><div class="shop-price">${item.price} ✦</div><h3>${item.name}</h3><strong class="shop-effect">${item.effect}</strong><p>${item.desc}</p><button ${disabled?'disabled':''} onclick="buyShopItem('${item.id}')">${label}</button></article>`;
}
function showShop(){if(!state.shopOpen){state.shopOpen=true;state.shopBought=new Set();}document.querySelector('#modal')?.remove();let w=WORLDS[state.world],budget=state.world===0?'First-shop earnings: 50 shards':'Earnings since the last shop: 75 shards';document.body.insertAdjacentHTML('beforeend',`<div class="overlay shop-overlay" id="modal"><section class="panel modal shop-modal"><div class="shop-heading"><div><div class="eyebrow">The elite path is clear</div><h2>The Wayfarer's Reliquary</h2><p>Prepare for ${w.mobs[4][0]}. Buy any relics you can afford—or save every shard for a stronger future shop.</p></div><div class="shop-wallet"><span>Echo shards</span><b>✦ ${state.shards}</b></div></div><div class="shop-income"><span>Shard rewards</span><b>Normal +10</b><i></i><b>Elite +20</b><i></i><b>Boss +25</b><small>${budget}</small></div><div class="shop-grid">${SHOP_ITEMS.map(shopItemMarkup).join('')}</div><div class="shop-footer"><small>Unused shards carry forward. Each relic can be purchased once per shop.</small><button class="primary" onclick="leaveShop()">Face the boss</button></div></section></div>`);}
function buyShopItem(id,heroId){let item=SHOP_ITEMS.find(x=>x.id===id);if(!state.shopOpen||!item||state.shopBought.has(id)||state.shards<item.price)return;if(id==='revive'){let hero=state.party.find(h=>h.id===heroId&&h.currentHp<=0);if(!hero)return;hero.currentHp=hero.maxHp;hero.burn=0;}else if(id==='heal'){if(!state.party.some(h=>h.currentHp>0&&h.currentHp<h.maxHp))return;state.party.filter(h=>h.currentHp>0).forEach(h=>h.currentHp=h.maxHp);}else if(id==='damage')state.pendingDamageBonus+=2;else if(id==='defense')state.pendingDefenseBonus+=2;state.shards-=item.price;state.shopBought.add(id);showShop();}
function advanceRun(campHeal=true){state.level++;if(state.level>4){state.world++;state.level=0;state.party.forEach(h=>h.currentHp=h.maxHp);state.log=[];}else if(campHeal)state.party.filter(h=>h.currentHp>0).forEach(h=>heal(h,8));startEncounter();}
function continueRun(){document.querySelector('#modal').remove();state.pendingReplacement=null;if(state.level===3){showShop();return;}advanceRun(true);}
function leaveShop(){document.querySelector('#modal')?.remove();state.shopOpen=false;advanceRun(false);}
function retainedAbility(h){return h.abilities.map((ability,index)=>({ability,index})).sort((a,b)=>(b.ability.rank||1)-(a.ability.rank||1)||b.index-a.index)[0]?.ability||h.start;}
function partyFell(){state.animating=false;state.fx=null;state.livesRemaining=Math.max(0,state.livesRemaining-1);state.pendingEchoOptions=state.party.map(h=>{let ability=retainedAbility(h);return {heroId:h.id,name:h.name,role:h.role,icon:h.icon,art:h.art,ability:{...ability,rank:ability.rank||1,desc:abilityText(ability)}};});render();showDeath();}
function showDeath(){let final=state.livesRemaining===0;document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><section class="panel modal defeat-modal"><div class="eyebrow">Life lost · ${state.livesRemaining}/5 remain</div><h2 class="death-title">${final?'The fifth flame is extinguished':'Your expedition has fallen'}</h2><p>${final?'The cycle closes, but one final memory can still be bound.':'Choose one hero to leave behind as an Echo. Their highest-ranked ability—and its current rank—will survive the fall.'}</p><div class="death-echo-grid">${state.pendingEchoOptions.map(e=>`<button class="death-echo-card" onclick="forgeEcho('${e.heroId}')"><span class="death-echo-art">${e.art?`<img src="${e.art}" alt="${e.name}" />`:e.icon}</span><span class="class">${e.role}</span><b>${e.name}'s Echo</b><small>${e.ability.icon} ${e.ability.name} · Rank ${e.ability.rank||1}</small><em>Bind this memory</em></button>`).join('')}</div><div class="life-loss-row">${[0,1,2,3,4].map(i=>`<i class="life ${i>=state.livesRemaining?'lost':''}"></i>`).join('')}</div></section></div>`)}
function forgeEcho(heroId){let option=state.pendingEchoOptions.find(e=>e.heroId===heroId);if(!option)return;let echo={...option,id:`echo-${++state.echoSerial}`};state.echoes.push(echo);if(state.equippedEchoIds.length<MAX_EQUIPPED_ECHOES)state.equippedEchoIds.push(echo.id);state.pendingEchoOptions=[];document.querySelector('#modal')?.remove();if(state.livesRemaining<=0){showFinalDefeat(echo);return;}reformParty();}
function reformParty(){state.level=0;state.selected=[];state.screen='select';state.party=[];state.rewards=[];state.pendingReplacement=null;state.learnedAbilities=new Set();state.cooldowns={};state.exhausted=new Set();render();}
function showFinalDefeat(echo){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><section class="panel modal final-defeat"><div class="eyebrow">No lives remain</div><h2 class="death-title">The campaign becomes an echo</h2><p>${echo.name}'s <b>${echo.ability.name}</b> survived at Rank ${echo.ability.rank||1}, but there is no living party left to carry it.</p><div class="final-echo">${echo.icon} ${echo.name}'s Echo · ${echo.ability.icon} ${echo.ability.name} R${echo.ability.rank||1}</div><button class="primary" onclick="location.reload()">Begin a new cycle</button></section></div>`)}
function castEchoEffect(e,multiplier=1,allowKill=false){let a=e.ability,target=currentTarget(),damage=Math.max(0,Math.floor((a.value||0)*multiplier)),restored=0,dealt=0;if(a.type==='heal'){let amount=Math.max(1,damage);state.party.filter(h=>h.currentHp>0).forEach(h=>{let before=h.currentHp;heal(h,amount);restored+=h.currentHp-before;});state.log.push(`<b>${e.name}'s Echo</b> restores ${restored} party health with ${a.name}.`);return;}if(target&&damage){let index=state.enemies.indexOf(target),before=target.hp,blocked=Math.min(target.armor||0,damage),impact=damage-blocked;target.armor-=blocked;target.hp=allowKill?target.hp-impact:Math.max(1,target.hp-impact);dealt=before-target.hp;if(blocked)state.log.push(`${target.name}'s armor blocks <b>${blocked}</b> Echo damage.`);if(state.fx){if(dealt)state.fx.enemyDamage.push({index,amount:dealt});if(!state.fx.hitTargets.includes(index))state.fx.hitTargets.push(index);if(before>0&&target.hp<=0)state.fx.defeated.push(index);}}if(a.heal){let amount=Math.max(1,Math.floor(a.heal*multiplier)),wounded=lowest(),before=wounded?.currentHp||0;heal(wounded,amount);restored=(wounded?.currentHp||0)-before;}if(multiplier>=1&&target?.hp>0){if(a.type==='poison')target.poison+=a.dot||3;if(a.type==='weaken')target.weakened=Math.max(target.weakened,a.weaken||4);if(a.type==='expose')target.expose=Math.max(target.expose,a.bonus||6);if(a.type==='evade')state.evade=state.intent?.targetId||nextLiving()?.id||null;if(a.type==='cry'){state.boost=2;state.boostPower=a.power||3;}}state.log.push(`<b>${e.name}'s Echo</b> casts ${a.name}${dealt?` for ${dealt} damage`:''}${restored?` and restores ${restored} health`:''}.`);}
function summonEcho(echoId){let e=state.echoes.find(echo=>echo.id===echoId&&state.equippedEchoIds.includes(echo.id));if(!e||state.echoUsed||state.animating||!currentTarget())return;state.echoUsed=true;state.animating=true;state.fx={kind:'hero',heroId:`echo:${e.id}`,abilityName:e.ability.name,enemyDamage:[],hitTargets:[],defeated:[],heals:[],heroDamages:[],heroDamage:null};castEchoEffect(e,1,true);if(!state.enemies[state.intent?.attackerIndex]||state.enemies[state.intent.attackerIndex].hp<=0)planEnemyIntent();render();if(state.enemies.every(enemy=>enemy.hp<=0)){setTimeout(victory,650);return;}setTimeout(()=>{state.animating=false;state.fx=null;render();},560);}
function endGame(){document.body.insertAdjacentHTML('beforeend',`<div class="overlay"><section class="panel modal"><div class="eyebrow">The cycle is broken</div><h2>Five worlds remember your name</h2><p>You defeated the End of Five with ${state.livesRemaining} lives and ${state.echoes.length} ${state.echoes.length===1?'Echo':'Echoes'} remaining in the archive.</p><button class="primary" onclick="location.reload()">Play another cycle</button></section></div>`)}
render();
